import {randomUUID} from 'node:crypto';
import type {FastifyInstance} from 'fastify';
import {parse, parseAllDocuments, stringify} from 'yaml';
import {z} from 'zod';
import type {EnvironmentService} from '../environment/environment.js';
import type {SshOperations, SshTarget} from '../../infrastructure/ssh.js';
import {shellQuote} from '../../infrastructure/ssh.js';

type JsonObject=Record<string,unknown>;
interface ResourceType{group:string;version:string;resource:string;kind:string;namespaced:boolean;verbs:string[];schemaAvailable:boolean;custom:boolean}
interface ResourceCoordinates{group:string;version:string;resource:string;namespace?:string|null|undefined;name:string}
interface ServiceSummary{key:string;name:string;source:string;status:string;resourceCount:number}
interface ResourceInventory{services:ServiceSummary[];groups:JsonObject[];resources:JsonObject[]}
const builtIn=new Set(['','apps','autoscaling','batch','networking.k8s.io','policy','rbac.authorization.k8s.io','storage.k8s.io','discovery.k8s.io','admissionregistration.k8s.io','apiextensions.k8s.io','coordination.k8s.io','events.k8s.io','scheduling.k8s.io','node.k8s.io']);
const coordinates=z.object({group:z.string().default(''),version:z.string().min(1),resource:z.string().min(1),namespace:z.string().nullable().optional(),name:z.string().min(1)}).strict();
const updateInput=z.object({environmentId:z.number().int().positive(),coordinates, yaml:z.string().min(1),expectedResourceVersion:z.string().min(1)}).strict();
const createInput=z.object({environmentId:z.number().int().positive(),namespace:z.string().min(1),serviceKey:z.string().min(1),yaml:z.string().min(1)}).strict();
export const containerKubectlCommand=(kubeconfig:string,args:string):string=>`kubectl --kubeconfig=${shellQuote(kubeconfig)} ${args}`;
export const containerNamespaceNames=(lines:string[]):string[]=>[...new Set(lines.map(line=>line.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));
const resourceIdentity=(kind:string,name:string)=>`${kind.toLowerCase()}/${name}`;
export function containerResourceOwnerHints(metadata:JsonObject){const labels=(metadata.labels??{}) as JsonObject,annotations=(metadata.annotations??{}) as JsonObject;return{
 releaseNames:[...new Set([annotations['meta.helm.sh/release-name'],annotations['helm.sh/release'],labels['app.kubernetes.io/instance'],labels.release].map(value=>String(value??'').trim()).filter(Boolean))],
 appNames:[...new Set([labels['app.kubernetes.io/name'],labels.app,labels['k8s-app']].map(value=>String(value??'').trim()).filter(Boolean))]
};}
export function propagateContainerResourceOwners(records:Array<{id:string;parentIds:string[];owners:Set<string>}>){const byId=new Map(records.map(record=>[record.id,record]));for(let pass=0;pass<records.length;pass++){let changed=false;for(const record of records)for(const parentId of record.parentIds)for(const owner of byId.get(parentId)?.owners??[]){if(!record.owners.has(owner)){record.owners.add(owner);changed=true;}}if(!changed)break;}return records;}

export class ContainerResourceService{
 private readonly kubectl:string;
 private readonly helm:string;
 private readonly cache=new Map<number,{expires:number,types:ResourceType[]}>();
 private readonly inventoryCache=new Map<string,{expires:number,value:ResourceInventory}>();
 constructor(private readonly environments:EnvironmentService,private readonly ssh:SshOperations,private readonly kubectlKubeconfig:string,helmKubeconfig:string){this.kubectl=containerKubectlCommand(kubectlKubeconfig,'').trimEnd();this.helm=`helm --kubeconfig=${shellQuote(helmKubeconfig)}`;}
 private target(id:number){const environment=this.environments.get(id);if(environment.type!=='CONTAINER')throw Object.assign(new Error('容器资源只能选择容器环境'),{statusCode:400});return this.environments.target(environment,'ROOT');}
 private command(target:SshTarget,args:string){return this.ssh.execute(target,containerKubectlCommand(this.kubectlKubeconfig,args));}
 private async json(target:SshTarget,args:string){const result=await this.command(target,args);if(result.exitCode!==0)throw Object.assign(new Error(`kubectl 执行失败：${result.lines.slice(-20).join('\n')}`),{statusCode:409});try{return JSON.parse(result.lines.join('\n')) as JsonObject;}catch{throw Object.assign(new Error('kubectl 返回了无效 JSON'),{statusCode:502});}}
 private async parallel<T,R>(items:T[],limit:number,work:(item:T)=>Promise<R>){const result=new Array<R>(items.length),next={value:0};await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(next.value<items.length){const index=next.value++;result[index]=await work(items[index]!);}}));return result;}
 async namespaces(environmentId:number){const target=this.target(environmentId),result=await this.command(target,"get namespaces --no-headers -o custom-columns=NAME:.metadata.name");if(result.exitCode!==0)throw Object.assign(new Error(`命名空间读取失败：${result.lines.slice(-20).join('\n')}`),{statusCode:409});const namespaces=containerNamespaceNames(result.lines);if(!namespaces.length)throw Object.assign(new Error('命名空间读取结果为空'),{statusCode:409});const environment=this.environments.get(environmentId);return{environmentId,environmentName:environment.name,namespaces};}
 async types(environmentId:number,refresh=false){if(!refresh){const item=this.cache.get(environmentId);if(item&&item.expires>Date.now())return item.types;}const target=this.target(environmentId);const schemas=new Set<string>();try{const index=await this.json(target,'get --raw /openapi/v3');for(const key of Object.keys((index.paths??{}) as JsonObject))schemas.add(key.replace(/^apis\//,'').replace(/^api\//,''));}catch{/* discovery remains usable */}
  const endpoints=['/api/v1'];const groups=await this.json(target,'get --raw /apis');for(const group of ((groups.groups??[]) as JsonObject[])){const value=((group.preferredVersion??{}) as JsonObject).groupVersion;if(value)endpoints.push(`/apis/${String(value)}`);}const types:ResourceType[]=[];
  const bodies=await this.parallel(endpoints,8,async endpoint=>({endpoint,body:await this.json(target,`get --raw ${shellQuote(endpoint)}`)}));for(const{endpoint,body}of bodies){const groupVersion=String(body.groupVersion??endpoint.slice(endpoint.lastIndexOf('/')+1));const slash=groupVersion.indexOf('/');const group=slash<0?'':groupVersion.slice(0,slash),version=slash<0?groupVersion:groupVersion.slice(slash+1);for(const item of (body.resources??[]) as JsonObject[]){const resource=String(item.name??'');if(!resource||resource.includes('/'))continue;types.push({group,version,resource,kind:String(item.kind??''),namespaced:Boolean(item.namespaced),verbs:((item.verbs??[]) as unknown[]).map(String).sort(),schemaAvailable:schemas.has(groupVersion),custom:!builtIn.has(group)});}}
  types.sort((a,b)=>a.group.localeCompare(b.group)||a.resource.localeCompare(b.resource));this.cache.set(environmentId,{expires:Date.now()+300_000,types});return types;}
 async inventory(environmentId:number,namespace:string,refresh=false){const cacheKey=`${environmentId}:${namespace}`;if(!refresh){const cached=this.inventoryCache.get(cacheKey);if(cached&&cached.expires>Date.now())return cached.value;}const target=this.target(environmentId),types=await this.types(environmentId,refresh);const helmResult=await this.ssh.execute(target,`${this.helm} list -n ${shellQuote(namespace)} -o json`).catch(()=>null);let releases:JsonObject[]=[];if(helmResult?.exitCode===0)try{const value=JSON.parse(helmResult.lines.join('\n'));if(Array.isArray(value))releases=value as JsonObject[];}catch{/* inventory still works without Helm ownership */}const owners=new Map<string,Set<string>>();const services=new Map<string,ServiceSummary>();
  for(const release of releases){const name=String(release.name??'');if(!name)continue;const key=`helm:${name}`;services.set(key,{key,name,source:'HELM',status:String(release.status??'UNKNOWN').toUpperCase(),resourceCount:0});const manifest=await this.ssh.execute(target,`${this.helm} get manifest ${shellQuote(name)} -n ${shellQuote(namespace)}`);if(manifest.exitCode===0)for(const doc of parseAllDocuments(manifest.lines.join('\n'))){const value=doc.toJSON() as JsonObject|undefined;const meta=value?.metadata as JsonObject|undefined;if(value?.kind&&meta?.name){const id=`${String(value.kind).toLowerCase()}/${String(meta.name)}`;const set=owners.get(id)??new Set<string>();set.add(key);owners.set(id,set);}}}
  const listTypes=types.filter(type=>type.verbs.includes('list')),listed=await this.parallel(listTypes,8,async type=>{const ns=type.namespaced?` -n ${shellQuote(namespace)}`:'';const list=await this.command(target,`get ${shellQuote(type.group?`${type.resource}.${type.group}`:type.resource)}${ns} -o json --ignore-not-found`);if(list.exitCode!==0)return{type,items:[] as JsonObject[]};try{const body=JSON.parse(list.lines.join('\n')) as JsonObject;return{type,items:(body.items??[]) as JsonObject[]};}catch{return{type,items:[] as JsonObject[]};}});
  const records=[] as Array<{type:ResourceType;item:JsonObject;name:string;kind:string;id:string;parentIds:string[];owners:Set<string>}>;for(const{type,items}of listed)for(const item of items){const meta=(item.metadata??{}) as JsonObject,name=String(meta.name??''),kind=String(item.kind??type.kind),id=resourceIdentity(kind,name),resourceOwners=new Set(owners.get(id)??[]),hints=containerResourceOwnerHints(meta);for(const releaseName of hints.releaseNames){const key=`helm:${releaseName}`;if(!services.has(key))services.set(key,{key,name:releaseName,source:'HELM',status:'UNKNOWN',resourceCount:0});resourceOwners.add(key);}if(!resourceOwners.size)for(const appName of hints.appNames){const match=[...services.values()].find(service=>service.name===appName);if(match)resourceOwners.add(match.key);}if(!resourceOwners.size&&['Deployment','StatefulSet','DaemonSet'].includes(kind)){const key=`workload:${name}`;services.set(key,{key,name,source:'WORKLOAD',status:this.workloadStatus(item),resourceCount:0});resourceOwners.add(key);}const references=(meta.ownerReferences??[]) as JsonObject[];records.push({type,item,name,kind,id,parentIds:references.map(reference=>resourceIdentity(String(reference.kind??''),String(reference.name??''))).filter(parent=>parent!=='/'),owners:resourceOwners});}
  propagateContainerResourceOwners(records);const summaries=[] as JsonObject[];for(const{type,item,name,kind,owners:resourceOwners}of records){for(const key of resourceOwners){const service=services.get(key);if(service)service.resourceCount++;}const groupType=!type.namespaced?'CLUSTER':resourceOwners.size>1?'SHARED':resourceOwners.size===0?'UNASSIGNED':'SERVICE';summaries.push({group:type.group,version:type.version,resource:type.resource,kind,name,category:this.category(kind,type.custom),status:['Deployment','StatefulSet','DaemonSet'].includes(kind)?this.workloadStatus(item):'NORMAL',custom:type.custom,editable:type.verbs.includes('update'),serviceKeys:[...resourceOwners],groupType});}
  const value:ResourceInventory={services:[...services.values()].sort((a,b)=>a.name.localeCompare(b.name)),groups:[{type:'SHARED',name:'共享资源',resourceCount:summaries.filter(i=>i.groupType==='SHARED').length},{type:'UNASSIGNED',name:'未分配资源',resourceCount:summaries.filter(i=>i.groupType==='UNASSIGNED').length},{type:'CLUSTER',name:'集群资源',resourceCount:summaries.filter(i=>i.groupType==='CLUSTER').length}],resources:summaries};this.inventoryCache.set(cacheKey,{expires:Date.now()+30_000,value});return value;}
 async workspace(environmentId:number,namespace:string,refresh=false){const inventory=await this.inventory(environmentId,namespace,refresh),environment=this.environments.get(environmentId);return{environmentId,environmentName:environment.name,namespace,services:inventory.services,groups:inventory.groups};}
 async serviceResources(environmentId:number,namespace:string,serviceKey:string){const inventory=await this.inventory(environmentId,namespace),group=serviceKey.startsWith('group:')?serviceKey.slice(6).toUpperCase():null,service=inventory.services.find(item=>item.key===serviceKey),groupSummary=group?inventory.groups.find(item=>item.type===group):undefined;if(!service&&!groupSummary)throw Object.assign(new Error('服务或资源分组不存在'),{statusCode:404});return{serviceKey,serviceName:service?.name??String(groupSummary!.name),resources:inventory.resources.filter(item=>group?item.groupType===group:(item.serviceKeys as string[]).includes(serviceKey)).map(({serviceKeys:_s,groupType:_g,...item})=>item)};}
 async read(environmentId:number,value:ResourceCoordinates){const target=this.target(environmentId),type=await this.resolveType(environmentId,value),ns=type.namespaced&&value.namespace?` -n ${shellQuote(value.namespace)}`:'';const body=await this.json(target,`get ${shellQuote(this.qualified(value))} ${shellQuote(value.name)}${ns} -o json`);const metadata=(body.metadata??{}) as JsonObject,labels=(metadata.labels??{}) as JsonObject,annotations=(metadata.annotations??{}) as JsonObject;const resourceVersion=String(metadata.resourceVersion??'');const managedByHelm=String(labels['app.kubernetes.io/managed-by']??annotations['app.kubernetes.io/managed-by']??'').toLowerCase()==='helm';delete body.status;for(const key of ['managedFields','uid','creationTimestamp','generation','selfLink'])delete metadata[key];return{coordinates:value,yaml:stringify(body),resourceVersion,managedByHelm};}
 async previewUpdate(input:z.infer<typeof updateInput>){const current=await this.read(input.environmentId,input.coordinates);this.assertVersion(current.resourceVersion,input.expectedResourceVersion);return this.withRemoteFile(input.environmentId,input.yaml,async(target,path)=>{await this.require(target,`${this.kubectl} replace --dry-run=server -f ${shellQuote(path)} -o yaml`,'服务端校验失败');const diff=await this.ssh.execute(target,`${this.kubectl} diff -f ${shellQuote(path)}`);if(![0,1].includes(diff.exitCode))throw Object.assign(new Error(`资源差异计算失败：${diff.lines.slice(-20).join('\n')}`),{statusCode:409});return{valid:true,diff:diff.lines.join('\n'),observedResourceVersion:current.resourceVersion,warnings:current.managedByHelm?['资源由 Helm 管理，手工修改可能在下一次发布时被覆盖']:[]};});}
 async applyUpdate(input:z.infer<typeof updateInput>){const current=await this.read(input.environmentId,input.coordinates);this.assertVersion(current.resourceVersion,input.expectedResourceVersion);return this.withRemoteFile(input.environmentId,input.yaml,async(target,path)=>{await this.require(target,`${this.kubectl} replace --dry-run=server -f ${shellQuote(path)} -o yaml`,'服务端校验失败');const latest=await this.read(input.environmentId,input.coordinates);this.assertVersion(latest.resourceVersion,input.expectedResourceVersion);await this.require(target,`${this.kubectl} replace -f ${shellQuote(path)}`,'资源更新失败');this.invalidateInventory(input.environmentId);const result=await this.read(input.environmentId,input.coordinates);return{coordinates:result.coordinates,resourceVersion:result.resourceVersion,yaml:result.yaml};});}
 async previewCreate(input:z.infer<typeof createInput>){const yaml=this.prepareCreate(input);return this.withRemoteFile(input.environmentId,yaml,async(target,path)=>{const result=await this.require(target,`${this.kubectl} create --dry-run=server -f ${shellQuote(path)} -o yaml`,'服务端校验失败');return{valid:true,diff:result.lines.map(line=>`+ ${line}`).join('\n'),observedResourceVersion:null,warnings:[]};});}
 async create(input:z.infer<typeof createInput>){const yaml=this.prepareCreate(input),document=parse(yaml) as JsonObject,meta=document.metadata as JsonObject;return this.withRemoteFile(input.environmentId,yaml,async(target,path)=>{await this.require(target,`${this.kubectl} create --dry-run=server -f ${shellQuote(path)} -o yaml`,'服务端校验失败');await this.require(target,`${this.kubectl} create -f ${shellQuote(path)}`,'资源创建失败');this.invalidateInventory(input.environmentId);const api=String(document.apiVersion??'v1'),slash=api.indexOf('/'),group=slash<0?'':api.slice(0,slash),version=slash<0?api:api.slice(slash+1),kind=String(document.kind??'');const type=(await this.types(input.environmentId,true)).find(item=>item.group===group&&item.version===version&&item.kind===kind);if(!type)throw new Error(`无法解析已创建资源类型：${api}/${kind}`);const result=await this.read(input.environmentId,{group,version,resource:type.resource,namespace:type.namespaced?input.namespace:null,name:String(meta.name)});return{coordinates:result.coordinates,resourceVersion:result.resourceVersion,yaml:result.yaml};});}
 private prepareCreate(input:z.infer<typeof createInput>){let value:JsonObject;try{value=parse(input.yaml) as JsonObject;}catch{throw Object.assign(new Error('资源 YAML 格式不正确'),{statusCode:400});}if(!value||typeof value!=='object'||!value.apiVersion||!value.kind)throw Object.assign(new Error('资源 YAML 必须包含 apiVersion 和 kind'),{statusCode:400});const metadata=((value.metadata??={}) as JsonObject);if(!metadata.name)throw Object.assign(new Error('资源 YAML 必须包含 metadata.name'),{statusCode:400});metadata.namespace=input.namespace;const labels=((metadata.labels??={}) as JsonObject);labels['app.kubernetes.io/name']=input.serviceKey.includes(':')?input.serviceKey.slice(input.serviceKey.indexOf(':')+1):input.serviceKey;return stringify(value);}
 private async resolveType(environmentId:number,value:ResourceCoordinates){const found=(await this.types(environmentId)).find(item=>item.group===value.group&&item.version===value.version&&item.resource===value.resource);if(!found)throw Object.assign(new Error('资源类型不存在'),{statusCode:404});return found;}
 private invalidateInventory(environmentId:number){for(const key of this.inventoryCache.keys())if(key.startsWith(`${environmentId}:`))this.inventoryCache.delete(key);}
 private qualified(value:ResourceCoordinates){return value.group?`${value.resource}.${value.group}`:value.resource;}
 private assertVersion(actual:string,expected:string){if(actual!==expected)throw Object.assign(new Error('资源已被其他操作修改，请刷新后重试'),{statusCode:409});}
 private async require(target:SshTarget,command:string,message:string){const result=await this.ssh.execute(target,command);if(result.exitCode!==0)throw Object.assign(new Error(`${message}：${result.lines.slice(-20).join('\n')}`),{statusCode:409});return result;}
 private async withRemoteFile<T>(environmentId:number,content:string,operation:(target:SshTarget,path:string)=>Promise<T>){const target=this.target(environmentId),directory=`/tmp/container-ops-resource-${randomUUID()}`,path=`${directory}/resource.yaml`;await this.ssh.uploadFiles(target,directory,new Map([['resource.yaml',Buffer.from(content)]]));try{return await operation(target,path);}finally{await this.ssh.execute(target,`rm -rf -- ${shellQuote(directory)}`).catch(()=>{});}}
 private workloadStatus(value:JsonObject){const status=(value.status??{}) as JsonObject,desired=Number(status.replicas??0),ready=Number(status.readyReplicas??0);return desired===0||desired===ready?'NORMAL':'ABNORMAL';}
 private category(kind:string,custom:boolean){if(custom)return'CUSTOM';if(['Deployment','StatefulSet','DaemonSet','ReplicaSet','Job','CronJob','Pod'].includes(kind))return'WORKLOAD';if(['ConfigMap','Secret','ServiceAccount'].includes(kind))return'CONFIG';if(['Service','Ingress','NetworkPolicy','EndpointSlice'].includes(kind))return'NETWORK';return'OTHER';}
}

export function containerResourceRoutes(app:FastifyInstance,service:ContainerResourceService){const query=z.object({environmentId:z.coerce.number().int().positive(),namespace:z.string().optional(),refresh:z.stringbool().default(false),serviceKey:z.string().optional(),group:z.string().default(''),version:z.string().optional(),resource:z.string().optional(),name:z.string().optional()});
 app.get('/api/container-resource-namespaces',async req=>service.namespaces(query.parse(req.query).environmentId));
 app.get('/api/container-resource-types',async req=>{const value=query.parse(req.query);return service.types(value.environmentId,value.refresh);});
 app.get('/api/container-resource-services',async req=>{const value=query.parse(req.query);if(!value.namespace)throw Object.assign(new Error('namespace 不能为空'),{statusCode:400});return service.workspace(value.environmentId,value.namespace,value.refresh);});
 app.get('/api/container-service-resources',async req=>{const value=query.parse(req.query);if(!value.namespace||!value.serviceKey)throw Object.assign(new Error('namespace 和 serviceKey 不能为空'),{statusCode:400});return service.serviceResources(value.environmentId,value.namespace,value.serviceKey);});
 app.get('/api/container-resources',async req=>{const value=query.parse(req.query);return service.read(value.environmentId,coordinates.parse({group:value.group,version:value.version,resource:value.resource,namespace:value.namespace,name:value.name}));});
 app.post('/api/container-resource-changes/preview',async req=>service.previewUpdate(updateInput.parse(req.body)));app.post('/api/container-resource-changes/apply',async req=>service.applyUpdate(updateInput.parse(req.body)));
 app.post('/api/container-resources/preview',async req=>service.previewCreate(createInput.parse(req.body)));app.post('/api/container-resources',async(req,reply)=>reply.code(201).send(await service.create(createInput.parse(req.body))));
}
