import {randomUUID} from 'node:crypto';
import {mkdir,readFile,readdir,writeFile} from 'node:fs/promises';
import {join,relative,resolve} from 'node:path';
import type {FastifyInstance} from 'fastify';
import {parse} from 'yaml';
import {z} from 'zod';
import type {TaskStore} from '../../platform/store.js';
import {durableSse} from '../../infrastructure/sse.js';
import type {SshOperations,SshTarget} from '../../infrastructure/ssh.js';
import {shellQuote} from '../../infrastructure/ssh.js';
import type {BuildArtifact,BuildService} from '../build/build.js';
import type {EnvironmentService} from '../environment/environment.js';

type Status='PENDING'|'ANALYZING'|'AWAITING_REVIEW'|'PREPARING'|'DEPLOYING'|'SUCCEEDED'|'FAILED';
type Stage='PENDING'|'ANALYZED'|'GENERATED'|'RENDERED'|'DEPLOYING'|'SUCCEEDED'|'FAILED';
interface ReplaceItem{location:string;key:string;oldValue:string;newValue:string}
interface PreparedService{service:string;stage:Stage;stageError:string|null;values:string;chart:string;templates:Record<string,string>;replaceItems:ReplaceItem[];unresolvedImages:string[];errors:string[]}
interface DeploymentEvent{sequence:number;occurredAt:string;stage:string;service:string|null;message:string}
interface DeploymentTask{id:string;mode:'QUICK'|'REVIEW';status:Status;artifactId:number;environmentId:number;module:string;namespace:string;revision:number;createdAt:string;startedAt:string|null;finishedAt:string|null;services:Record<string,PreparedService|null>;events:DeploymentEvent[];sequence:number}
interface Container{pod:string;container:string;phase:string;ready:boolean;image:string}
const name=z.string().regex(/^[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?$/);
const createInput=z.object({mode:z.enum(['QUICK','REVIEW']),artifactId:z.number().int().positive(),environmentId:z.number().int().positive(),namespace:name,services:z.array(name).min(1)}).strict();
const KUBECTL='kubectl --kubeconfig=/root/.kube/config',HELM='helm --kubeconfig=/opt/kubeconfig/kubeconfig.txt';
const chartsRoot=resolve('data/deployment-preparations');
const groupKinds:Record<string,string>={BeidouLog:'beidoulog',DrPodAutoscaler:'drpodautoscaler',MqsClient:'mqsclient',SOPPub:'soppub',SopSecret:'sopsecret',ResourceClaim:'resourceclaim.resource.sop.huawei.com',LogResourceClaim:'logresourceclaim.resource.sop.huawei.com'};

export class DeploymentService{
 private readonly running=new Set<string>();
 constructor(private readonly store:TaskStore,private readonly builds:BuildService,private readonly environments:EnvironmentService,private readonly ssh:SshOperations){for(const task of this.tasks().filter(item=>['ANALYZING','PREPARING','DEPLOYING'].includes(item.status))){task.status='FAILED';task.finishedAt=new Date().toISOString();this.emit(task,'SYSTEM',null,'服务重启，原部署进程已中断');this.save(task);}}
 private artifact(id:number){return this.builds.artifact(id);}
 private buildTarget(artifact:BuildArtifact){const environment=this.environments.get(artifact.buildEnvironmentId);if(environment.type!=='BUILD')throw new Error('构建产物关联的构建环境不存在');return this.environments.target(environment,'HUAWEI');}
 private deployTarget(id:number){const environment=this.environments.get(id);if(environment.type!=='CONTAINER')throw Object.assign(new Error('部署只能选择容器环境'),{statusCode:400});return this.environments.target(environment,'ROOT');}
 tasks(){return this.store.records<DeploymentTask>('deployment-task');}get(id:string){const task=this.store.getRecord<DeploymentTask>('deployment-task',id);if(!task)throw Object.assign(new Error('部署任务不存在或已过期'),{statusCode:404});return task;}
 private save(task:DeploymentTask){this.store.putRecord('deployment-task',task.id,task,task.createdAt);}
 private emit(task:DeploymentTask,stage:string,service:string|null,message:string){task.events.push({sequence:++task.sequence,occurredAt:new Date().toISOString(),stage,service,message});if(task.events.length>10000)task.events.shift();this.save(task);}
 events(id:string,after:number){return this.get(id).events.filter(e=>e.sequence>after);}terminal(id:string){return ['SUCCEEDED','FAILED'].includes(this.get(id).status);}
 private async command(target:SshTarget,command:string,timeout=120000,onLine:(line:string)=>void=()=>{}){const result=await this.ssh.execute(target,command,onLine,undefined,timeout);return{code:result.exitCode,output:result.lines.map(line=>line.replace(/^\[stderr\] /,'')).join('\n')};}
 private async require(target:SshTarget,command:string,message:string,task?:DeploymentTask,service?:string,timeout=120000){try{const result=await this.command(target,command,timeout,line=>{if(task)this.emit(task,'LOG',service??null,line);});if(result.code!==0)throw new Error(`${message}：${result.output.slice(-1000)}`);return result.output;}catch(error){throw Object.assign(new Error(error instanceof Error?error.message:message),{statusCode:409});}}
 private async list(target:SshTarget,path:string,type:'d'|'f'){const output=await this.require(target,`find ${shellQuote(path)} -mindepth 1 -maxdepth 1 -type ${type} -printf '%f\\n' | sort`,'远程目录读取失败');return output.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);}
 async candidates(artifactId:number,environmentId:number,namespace?:string){const artifact=this.artifact(artifactId),build=this.buildTarget(artifact),target=this.deployTarget(environmentId);const services=await this.list(build,artifact.remoteChartsRoot,'d'),namespaces=(await this.require(target,`${KUBECTL} get namespaces --no-headers -o custom-columns=NAME:.metadata.name`,'命名空间读取失败')).split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(!namespaces.length)throw new Error('命名空间读取结果为空');let workloads:Array<{name:string;kind:string;deployable:boolean}>=[];
  if(namespace){if(!namespaces.includes(namespace))throw Object.assign(new Error(`命名空间不存在：${namespace}`),{statusCode:400});const containers=this.runtimeContainers(await this.require(target,this.podCommand(namespace),'命名空间 Pod 读取失败'));const available=services.filter(service=>containers.some(item=>item.pod.startsWith(`${service}-`)));const output=await this.require(target,`${KUBECTL} get deployment,statefulset -n ${shellQuote(namespace)} -o go-template=${shellQuote('{{range .items}}{{printf "%s\\t%s\\n" .kind .metadata.name}}{{end}}')}`,'工作负载读取失败');const kinds=new Map(output.split(/\r?\n/).filter(Boolean).map(line=>{const[kind,value]=line.split('\t');return[value!,kind==='StatefulSet'?'STATEFUL_SET':kind==='Deployment'?'DEPLOYMENT':'UNKNOWN'];}));workloads=available.map(service=>({name:service,kind:kinds.get(service)??'UNKNOWN',deployable:true}));}return{module:artifact.module,workloads,namespaces};}
 start(input:unknown){const value=createInput.parse(input),artifact=this.artifact(value.artifactId);this.deployTarget(value.environmentId);const now=new Date().toISOString(),services=Object.fromEntries([...new Set(value.services)].map(service=>[service,null]));const task:DeploymentTask={id:randomUUID(),mode:value.mode,status:'PENDING',artifactId:value.artifactId,environmentId:value.environmentId,module:artifact.module,namespace:value.namespace,revision:1,createdAt:now,startedAt:null,finishedAt:null,services,events:[],sequence:0};this.save(task);this.emit(task,'ANALYZE',null,'部署任务已创建');this.running.add(task.id);void this.analyze(task,artifact).finally(()=>this.running.delete(task.id));return this.response(task);}
 response(task:DeploymentTask){const{events:_e,sequence:_s,...value}=task;const services=Object.fromEntries(Object.entries(value.services).map(([key,item])=>[key,item?(({chart:_c,templates:_t,...visible})=>visible)(item):null]));return{...value,services};}
 updateValues(id:string,service:string,values:string){const task=this.get(id),prepared=task.services[service];if(task.mode!=='REVIEW'||task.status!=='AWAITING_REVIEW'||!prepared)throw Object.assign(new Error('当前部署任务不能修改 values'),{statusCode:409});if(prepared.values===values)return this.response(task);const inspection=this.inspectValues(values);prepared.values=values;prepared.unresolvedImages=inspection.unresolvedImages;prepared.errors=inspection.errors;prepared.stage=inspection.errors.length?'FAILED':'ANALYZED';prepared.stageError=null;task.revision++;this.emit(task,'EDIT',service,inspection.unresolvedImages.length?`values.yaml 已更新，仍有未解析镜像：${inspection.unresolvedImages.join('、')}`:'values.yaml 已更新，可以确认配置并部署');return this.response(task);}
 execute(id:string,revision:number){const task=this.get(id);if(task.mode!=='REVIEW')throw Object.assign(new Error('快速部署不能人工执行'),{statusCode:409});if(task.startedAt&&task.revision===revision)return this.response(task);if(task.status!=='AWAITING_REVIEW'||task.revision!==revision||Object.values(task.services).some(item=>!item||item.errors.length||this.unresolved(item.values)||item.stage!=='ANALYZED'))throw Object.assign(new Error('部署配置已变化或尚未完成分析'),{statusCode:409});task.status='PREPARING';task.startedAt=new Date().toISOString();this.save(task);this.running.add(id);void this.prepareAndDeploy(task).finally(()=>this.running.delete(id));return this.response(task);}
 private async analyze(task:DeploymentTask,artifact:BuildArtifact){task.status='ANALYZING';this.save(task);const build=this.buildTarget(artifact),target=this.deployTarget(task.environmentId),sources=new Map<string,{values:string;chart:string}>();let global='';try{global=await this.ssh.readText(build,`${artifact.remoteModuleRoot}/values.yaml`);for(const service of Object.keys(task.services)){this.emit(task,'ANALYZE',service,'正在读取待补全配置');const root=`${artifact.remoteChartsRoot}/${service}`;sources.set(service,{values:await this.ssh.readText(build,`${root}/values.yaml`),chart:await this.ssh.readText(build,`${root}/Chart.yaml`)});}}catch(error){return this.failAll(task,error);}
  const requirements=[...sources.values()].map(source=>this.requirements(source.values,source.chart,global)),needsRuntime=requirements.some(item=>item.packages||item.jars),needsPackages=requirements.some(item=>item.packages),needsHelm=requirements.some(item=>item.helm);let containers:Container[]=[];try{if(needsRuntime)containers=this.runtimeContainers(await this.require(target,this.podCommand(task.namespace),'命名空间 Pod 读取失败'));}catch(error){return this.failAll(task,error);}let architecture='';try{if(needsPackages)architecture=this.architecture((await this.require(target,'uname -m','环境架构读取失败')).trim());}catch(error){return this.failAll(task,error);}let helmValues:Record<string,unknown>={};try{if(needsHelm){const releases=(await this.require(target,`${HELM} list -n ${shellQuote(task.namespace)} -q`,'Helm release 列表读取失败')).split(/\r?\n/).filter(Boolean),release=[`${task.module}chart`,`${task.module.replaceAll('-','')}chart`].find(value=>releases.includes(value));if(!release)throw new Error(`未找到模块 ${task.module} 对应的 Helm release`);helmValues=JSON.parse(await this.require(target,`${HELM} get values ${shellQuote(release)} -a -n ${shellQuote(task.namespace)} -o json`,'Helm values 读取失败')) as Record<string,unknown>;}}catch(error){return this.failAll(task,error);}
  for(const[service,source]of sources){try{const requirement=this.requirements(source.values,source.chart,global);let packages:Record<string,string>={},jars='';if(requirement.packages||requirement.jars){const identity=this.identity(source.values),container=this.targetContainer(identity,containers),script=[requirement.packages?`printf '%s\\n' __COK_LOCK__; cat /opt/pkg_version/lock.json`:null,requirement.jars?`printf '\\n%s\\n' __COK_JAR__; test ! -r /opt/pkg_version/jarlist.json || cat /opt/pkg_version/jarlist.json`:null].filter(Boolean).join('; '),output=await this.require(target,`${KUBECTL} exec -n ${shellQuote(task.namespace)} ${shellQuote(container.pod)} -c ${shellQuote(container.container)} -- sh -c ${shellQuote(script)}`,`${service} 容器版本信息读取失败`);if(requirement.packages)packages=this.packageVersions(this.section(output,'__COK_LOCK__',requirement.jars?'__COK_JAR__':undefined),architecture);if(requirement.jars)jars=this.section(output,'__COK_JAR__');}const environment=this.helmEnvironment(helmValues),prepared=this.prepare(service,source.values,source.chart,global,packages,environment.versions,environment.overrides,jars);task.services[service]=prepared;this.emit(task,'ANALYZE',service,prepared.errors.length?prepared.errors.join('；'):'自动补全完成');}catch(error){task.services[service]=this.failedService(service,error);this.emit(task,'ANALYZE',service,this.failure(error));}}
  const failed=Object.values(task.services).some(item=>!item||item.errors.length)||(task.mode==='QUICK'&&Object.values(task.services).some(item=>item&&this.unresolved(item.values)));if(failed){task.status='FAILED';task.finishedAt=new Date().toISOString();this.save(task);return;}if(task.mode==='REVIEW'){task.status='AWAITING_REVIEW';this.save(task);return;}task.status='PREPARING';task.startedAt=new Date().toISOString();this.save(task);await this.prepareAndDeploy(task);}
 private failAll(task:DeploymentTask,error:unknown){for(const service of Object.keys(task.services)){task.services[service]=this.failedService(service,error);this.emit(task,'ANALYZE',service,this.failure(error));}task.status='FAILED';task.finishedAt=new Date().toISOString();this.save(task);}
 private failedService(service:string,error:unknown):PreparedService{return{service,stage:'FAILED',stageError:null,values:'',chart:'',templates:{},replaceItems:[],unresolvedImages:[],errors:[this.failure(error)]};}
 private async prepareAndDeploy(task:DeploymentTask){const artifact=this.artifact(task.artifactId),build=this.buildTarget(artifact),target=this.deployTarget(task.environmentId);for(const[service,item]of Object.entries(task.services)){if(!item||item.stage!=='ANALYZED')continue;try{item.templates=await this.templates(build,artifact,service);await this.writeWorkspace(task.id,item);item.stage='GENERATED';this.emit(task,'APPLY',service,'Chart 已生成到本地工作目录');}catch(error){item.stage='FAILED';item.stageError=this.failure(error);this.emit(task,'APPLY',service,item.stageError);}}
  if(Object.values(task.services).some(item=>item?.stage!=='GENERATED'))return this.finish(task);for(const[service,item]of Object.entries(task.services)){try{const dir=await this.upload(task,target,service,item!);await this.require(target,`${HELM} template ${shellQuote(service)} ${shellQuote(dir)} -f ${shellQuote(`${dir}/values.yaml`)} -n ${shellQuote(task.namespace)}`,'Helm 渲染校验失败',task,service);item!.stage='RENDERED';this.emit(task,'RENDER',service,'Helm 渲染校验通过');}catch(error){item!.stage='FAILED';item!.stageError=this.failure(error);this.emit(task,'RENDER',service,item!.stageError);}}
  if(Object.values(task.services).some(item=>item?.stage!=='RENDERED'))return this.finish(task);task.status='DEPLOYING';this.save(task);for(const[service,item]of Object.entries(task.services)){try{item!.stage='DEPLOYING';this.emit(task,'DEPLOY',service,'[1/5] 再次执行渲染校验');const dir=await this.upload(task,target,service,item!),rendered=await this.require(target,`${HELM} template ${shellQuote(service)} ${shellQuote(dir)} -f ${shellQuote(`${dir}/values.yaml`)} -n ${shellQuote(task.namespace)}`,'渲染校验失败',task,service);this.emit(task,'DEPLOY',service,'[2/5] 卸载旧 release');await this.require(target,`if ${HELM} status ${shellQuote(service)} -n ${shellQuote(task.namespace)} >/dev/null 2>&1; then ${HELM} uninstall ${shellQuote(service)} -n ${shellQuote(task.namespace)}; fi`,'旧 release 卸载失败',task,service,180000);this.emit(task,'DEPLOY',service,'[3/5] 释放其它 release 占用的同名资源');await this.releaseConflicts(target,task,service,rendered);this.emit(task,'DEPLOY',service,'[4/5] 安装 Helm release');await this.require(target,`${HELM} install ${shellQuote(service)} ${shellQuote(dir)} -f ${shellQuote(`${dir}/values.yaml`)} -n ${shellQuote(task.namespace)}`,'安装失败',task,service,300000);this.emit(task,'DEPLOY',service,'[5/5] 等待工作负载就绪');await this.waitReady(target,task,service);item!.stage='SUCCEEDED';item!.stageError=null;this.emit(task,'DEPLOY',service,'部署成功');}catch(error){item!.stage='FAILED';item!.stageError=this.failure(error);this.emit(task,'DEPLOY',service,`部署失败：${item!.stageError}`);}}
  this.finish(task);}
 private finish(task:DeploymentTask){task.status=Object.values(task.services).every(item=>item?.stage==='SUCCEEDED')?'SUCCEEDED':'FAILED';task.finishedAt=new Date().toISOString();this.save(task);}
 private async templates(target:SshTarget,artifact:BuildArtifact,service:string){const output:Record<string,string>={},servicePath=`${artifact.remoteChartsRoot}/${service}/templates`;for(const file of await this.list(target,servicePath,'f'))if(!file.startsWith('_'))output[file]=await this.ssh.readText(target,`${servicePath}/${file}`);const modulePath=`${artifact.remoteModuleRoot}/templates`;for(const file of await this.list(target,modulePath,'f'))if(file.startsWith('_')&&!output[file])output[file]=await this.ssh.readText(target,`${modulePath}/${file}`);return output;}
 private async writeWorkspace(taskId:string,item:PreparedService){const root=resolve(chartsRoot,taskId,item.service);if(relative(chartsRoot,root).startsWith('..'))throw new Error('Chart 工作目录不正确');await mkdir(join(root,'templates'),{recursive:true});await writeFile(join(root,'values.yaml'),item.values);await writeFile(join(root,'Chart.yaml'),item.chart);for(const[file,content]of Object.entries(item.templates)){const path=resolve(root,'templates',file);if(relative(join(root,'templates'),path).startsWith('..'))throw new Error('模板文件名格式不正确');await writeFile(path,content);}}
 private async files(root:string,prefix=''){const result=new Map<string,Buffer>();for(const item of await readdir(root,{withFileTypes:true})){const name=prefix?`${prefix}/${item.name}`:item.name,path=join(root,item.name);if(item.isDirectory())for(const entry of await this.files(path,name))result.set(entry[0],entry[1]);else result.set(name,await readFile(path));}return result;}
 private async upload(task:DeploymentTask,target:SshTarget,service:string,item:PreparedService){const directory=`/tmp/container-ops-kit/${task.id}/${service}`;await this.require(target,`rm -rf -- ${shellQuote(directory)} && mkdir -p ${shellQuote(directory)}`,'Chart 远程目录准备失败');await this.ssh.uploadFiles(target,directory,await this.files(resolve(chartsRoot,task.id,item.service)));return directory;}
 private async releaseConflicts(target:SshTarget,task:DeploymentTask,release:string,manifest:string){const seen=new Set<string>(),pattern=/^kind:\s*([^\s]+)[\s\S]*?^metadata:\s*\n(?:^[ \t]+.*\n)*?^[ \t]+name:\s*([^\s#]+)/gm;for(const match of manifest.matchAll(pattern)){const kind=match[1]!,name=match[2]!,resource=groupKinds[kind]??kind.toLowerCase(),key=`${resource}/${name}`;if(seen.has(key))continue;seen.add(key);const owner=(await this.command(target,`${KUBECTL} get ${shellQuote(resource)} ${shellQuote(name)} -n ${shellQuote(task.namespace)} -o jsonpath='{.metadata.annotations.meta\\.helm\\.sh/release-name}' 2>/dev/null || true`)).output.trim();if(owner&&owner!==release)await this.require(target,`${KUBECTL} delete ${shellQuote(resource)} ${shellQuote(name)} -n ${shellQuote(task.namespace)} --ignore-not-found`,'冲突资源删除失败',task,release);}}
 private async waitReady(target:SshTarget,task:DeploymentTask,service:string){const deadline=Date.now()+600000;while(Date.now()<deadline){const value=await this.command(target,`for t in deployment statefulset; do ${KUBECTL} get $t ${shellQuote(service)} -n ${shellQuote(task.namespace)} -o jsonpath='{.status.readyReplicas}/{.status.replicas}' 2>/dev/null && exit 0; done; exit 1`);if(value.code===0&&/^([1-9]\d*)\/\1$/.test(value.output.trim()))return;await new Promise(resolve=>setTimeout(resolve,15000));}throw new Error('等待工作负载就绪超时');}
 private podCommand(namespace:string){return`${KUBECTL} get pods -n ${shellQuote(namespace)} -o go-template=${shellQuote('{{range .items}}{{if not .metadata.deletionTimestamp}}{{$pod := .}}{{range .status.containerStatuses}}{{printf "%s\\t%s\\t%s\\t%t\\t%s\\n" $pod.metadata.name .name $pod.status.phase .ready .imageID}}{{end}}{{end}}{{end}}')}`;}
 private runtimeContainers(text:string){return text.split(/\r?\n/).filter(Boolean).map(line=>{const values=line.split('\t');if(values.length!==5)throw new Error(`Pod 精简列表格式不正确：${line}`);return{pod:values[0]!,container:values[1]!,phase:values[2]!,ready:values[3]==='true',image:values[4]!};});}
 private identity(values:string){const value=parse(values) as Record<string,unknown>,appg=value?.appg as Record<string,unknown>|undefined,workload=String(appg?.name??'');const matches=[...values.matchAll(/processName\s*:\s*['"]?([^\s'"#]+)/g)].map(m=>m[1]!);if(!workload||new Set(matches).size!==1)throw new Error('values.yaml appg.name 或 processName 配置无效');return{workload,container:matches[0]!};}
 private targetContainer(identity:{workload:string;container:string},items:Container[]){const matches=items.filter(item=>item.pod.startsWith(`${identity.workload}-`)&&item.container===identity.container&&item.phase==='Running'&&item.ready).sort((a,b)=>a.pod.localeCompare(b.pod));if(!matches.length)throw new Error(`工作负载 ${identity.workload} 没有 Running/Ready 的容器 ${identity.container}`);if(new Set(matches.map(item=>item.image)).size>1)throw new Error(`工作负载 ${identity.workload} 的 Ready 副本镜像不一致`);return matches[0]!;}
 private packageVersions(text:string,architecture:string){let body:Record<string,unknown>;try{body=JSON.parse(text) as Record<string,unknown>;}catch{throw new Error('lock.json 不是有效 JSON');}if(!Array.isArray(body.packages))throw new Error('lock.json 缺少 packages 数组');const result:Record<string,string>={};for(const value of body.packages as Record<string,unknown>[])if(String(value.arch)===architecture){const name=String(value.name??''),version=String(value.version??'');if(name&&version&&result[name]&&result[name]!==version)throw new Error(`lock.json 中 ${name}/${architecture} 存在多个版本`);if(name&&version)result[name]=version;}if(!Object.keys(result).length)throw new Error(`lock.json 中不存在架构 ${architecture} 的包版本`);return result;}
 private helmEnvironment(body:Record<string,unknown>){const global=(body.global??{}) as Record<string,unknown>,versions:Record<string,string>={},overrides:Record<string,string>={};for(const value of Object.values((global.image??{}) as Record<string,Record<string,unknown>>)){const name=String(value?.name??''),version=String(value?.version??'');if(name&&version)versions[name]=version;}for(const key of ['nodePool','domains'])if(global[key]!=null)overrides[key]=typeof global[key]==='object'?JSON.stringify(global[key]):String(global[key]);const repo=(global.repo??{}) as Record<string,unknown>;if(repo.address!=null)overrides['repo.address']=String(repo.address);return{versions,overrides};}
 private prepare(service:string,values:string,chart:string,global:string,packages:Record<string,string>,environment:Record<string,string>,overrides:Record<string,string>,jars:string):PreparedService{const replacements:ReplaceItem[]=[],unresolvedImages:string[]=[];let result=global.trim()?global.trimEnd()+'\n'+values.replace(/^global:\s*[\s\S]*?(?=^[A-Za-z0-9_.-]+:|$)/m,'').trimStart():values;for(const[key,value]of Object.entries(overrides)){const simple=key.includes('.')?key.slice(key.lastIndexOf('.')+1):key;result=result.replace(new RegExp(`^(\\s*${simple}\\s*:\\s*)([^#\\n]*)(.*)$`,'m'),(_all,prefix,old,suffix)=>{replacements.push({location:'values.yaml',key:`global.${key}`,oldValue:String(old).trim(),newValue:value});return`${prefix}'${value.replaceAll("'","''")}'${suffix}`;});}result=result.replace(/\{version:([A-Za-z0-9_.-]+)}/g,(full,key:string)=>{const value=environment[key];if(!value){unresolvedImages.push(key);return full;}replacements.push({location:'values.yaml',key:`version.${key}`,oldValue:full,newValue:value});return value;});const version=packages[service];if(version){result=result.replace(/\{version}/g,()=>{replacements.push({location:'values.yaml',key:service,oldValue:'{version}',newValue:version});return version;});chart=chart.replaceAll('{version}',version);}if(jars.trim())result=result.replace(/replaceByBuild/g,()=>{const value=`'${jars.trim().replaceAll("'","''")}'`;replacements.push({location:'values.yaml',key:`jars.${service}`,oldValue:'replaceByBuild',newValue:value});return value;});const errors=[...new Set([...result.matchAll(/\{[A-Za-z0-9_:.-]+}|replaceByOssDiy/g)].map(m=>m[0]).filter(v=>!/^\{version:[^}]+}$/.test(v)||!unresolvedImages.includes(v.slice(9,-1))).map(v=>`存在未解析占位符：${v}`))];return{service,stage:errors.length?'FAILED':'ANALYZED',stageError:null,values:result,chart,templates:{},replaceItems:replacements,unresolvedImages:[...new Set(unresolvedImages)],errors};}
 private section(text:string,start:string,end?:string){const begin=text.indexOf(start);if(begin<0)throw new Error(`容器版本信息缺少分段标记：${start}`);const from=begin+start.length,to=end?text.indexOf(end,from):text.length;if(to<0)throw new Error(`容器版本信息缺少分段标记：${end}`);return text.slice(from,to).trim();}
 private requirements(values:string,chart:string,global:string){const all=`${values}\n${chart}\n${global}`;return{packages:all.includes('{version}'),jars:values.includes('replaceByBuild'),helm:/\{version:[A-Za-z0-9_.-]+}/.test(all)||/^[ \t]*(nodePool|domains|repo)[ \t]*:/m.test(global)};}
 private inspectValues(value:string){const unresolvedImages=[...new Set([...value.matchAll(/\{version:([A-Za-z0-9_.-]+)}/g)].map(match=>match[1]!))],errors=[...new Set([...value.matchAll(/\{[A-Za-z0-9_:.-]+}|replaceByOssDiy/g)].map(match=>match[0]).filter(marker=>!/^\{version:[^}]+}$/.test(marker)).map(marker=>`存在未解析占位符：${marker}`))];return{unresolvedImages,errors};}
 private unresolved(value:string){return /\{[A-Za-z0-9_:.-]+}|replaceByOssDiy/.test(value);}private architecture(value:string){return value==='amd64'?'x86_64':value==='arm64'?'aarch64':value;}private failure(error:unknown){return error instanceof Error?error.message:String(error);}
}

export function deploymentRoutes(app:FastifyInstance,service:DeploymentService){const id=(p:unknown)=>z.object({id:z.uuid()}).parse(p).id;app.get('/api/deployment-candidates',async req=>{const value=z.object({artifactId:z.coerce.number().int().positive(),environmentId:z.coerce.number().int().positive(),namespace:z.string().optional()}).parse(req.query);return service.candidates(value.artifactId,value.environmentId,value.namespace);});app.post('/api/deployment-tasks',async(req,reply)=>reply.code(202).send(service.start(req.body)));app.get('/api/deployment-tasks/:id',async req=>service.response(service.get(id(req.params))));app.put('/api/deployment-tasks/:id/services/:service/values',async req=>{const params=z.object({id:z.uuid(),service:name}).parse(req.params),body=z.object({values:z.string()}).strict().parse(req.body);return service.updateValues(params.id,params.service,body.values);});app.post('/api/deployment-tasks/:id/execution',async(req,reply)=>{const body=z.object({expectedRevision:z.number().int().positive()}).strict().parse(req.body);return reply.code(202).send(service.execute(id(req.params),body.expectedRevision));});app.get('/api/deployment-tasks/:id/events',async(req,reply)=>{const taskId=id(req.params);service.get(taskId);const query=z.object({afterSequence:z.coerce.number().int().min(0).default(0)}).parse(req.query),header=z.coerce.number().int().min(0).parse(req.headers['last-event-id']??0);durableSse(reply,n=>service.events(taskId,n),()=>service.terminal(taskId),Math.max(query.afterSequence,header));});}
