create table release_version (
  id bigint generated by default as identity primary key,
  code varchar(32) not null unique,
  name varchar(128) not null,
  sort_order int not null
);

create table environment (
  id bigint generated by default as identity primary key,
  release_version_id bigint not null,
  type varchar(16) not null,
  name varchar(128) not null,
  host varchar(255) not null,
  ssh_port int not null,
  password varchar(512) not null,
  work_directory varchar(512),
  architecture varchar(32),
  mae varchar(255),
  mae_user varchar(128),
  mae_password varchar(512),
  osmu varchar(255),
  osmu_user varchar(128),
  osmu_password varchar(512),
  connection_status varchar(16) not null,
  last_tested_at timestamp,
  last_test_latency_ms bigint,
  last_test_error varchar(1000),
  created_at timestamp not null,
  updated_at timestamp not null,
  version bigint not null,
  constraint fk_environment_version foreign key (release_version_id) references release_version(id)
);

insert into release_version(code, name, sort_order) values ('R27C10', 'R27C10', 1);
insert into release_version(code, name, sort_order) values ('R27C00', 'R27C00', 2);