create table build_artifact (
  id bigint generated by default as identity primary key,
  build_task_id varchar(64) not null unique,
  build_environment_id bigint not null,
  module varchar(128) not null,
  cbb_web_dev_branch varchar(255) not null,
  arch_design_branch varchar(255) not null,
  remote_task_root varchar(1000) not null,
  remote_arch_design_root varchar(1000) not null,
  remote_module_root varchar(1000) not null,
  remote_charts_root varchar(1000) not null,
  created_at timestamp not null,
  constraint fk_build_artifact_environment foreign key (build_environment_id) references environment(id)
);
