import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const html=await readFile(new URL('../../index.html',import.meta.url),'utf8');
const config={versions:[{version:'R27C10',baseBranch:'release/27'},{version:'R27C00',baseBranch:'release/26'}],dateMode:'yesterday',username:'tester',ticket:'DTS1',workspaceRoot:'/tmp',schedule:{enabled:false,frequency:'weekdays',weekday:1,time:'09:00',timezone:'Asia/Shanghai',action:'FETCH'}};
const settings={url:'http://grafana/api/tsdb/query',datasourceId:4,timeoutSeconds:60,parallel:2,auth:'none'};
const pause=()=>new Promise(r=>setTimeout(r,10));
function page(extra,url='http://localhost'){return new JSDOM(html,{runScripts:'dangerously',url,beforeParse(w){w.scrollTo=()=>{};w.fetch=async(path,options)=>({ok:true,status:200,json:async()=>{const result=extra?.(path,options);if(result!==undefined)return result;if(path==='/api/auto-ut/report-settings')return{config:structuredClone(config),nextRunAt:null};if(path==='/api/quality/settings')return settings;if(path==='/api/auto-ut/schedule')return null;return[];}});}});}
function open(dom,name){const d=dom.window.document;d.querySelector('[data-platform-domain="automation"]').click();d.querySelector(`[data-automation-capability="${name}"]`).click();return d;}
test('Auto-UT 获取按钮保存多版本分支并按版本选择修复，无转入按钮',async()=>{
 const calls=[];let captured;const run={id:'r1',jobId:'q1',status:'READY',createdAt:'2026-09-20',config,trigger:'MANUAL',messages:[],claimed:[],taskIds:[],plan:config.versions.map(v=>({version:v.version,repository:'Demo',baseBranch:v.baseBranch,repairBranch:v.baseBranch+'_tester_DTS1_'+v.version,failedTests:1,lineCoverage:.5,lineGoal:.8,configured:true,repositoryUrl:'ssh://git@example/Demo.git'}))};
 const dom=page((path,o)=>{calls.push(path);if(path==='/api/auto-ut/report-settings'&&o?.method==='PUT'){captured=JSON.parse(o.body);return{config:captured,nextRunAt:null};}if(path==='/api/auto-ut/reports'&&o?.method==='POST')return run;if(path==='/api/auto-ut/reports/r1/tasks'){assert.deepEqual(JSON.parse(o.body).selected,['R27C00/Demo']);return run;}});
 try{const d=open(dom,'auto-ut');await pause();d.querySelector('[data-qw-drawer="versions"]').click();assert.equal(d.querySelectorAll('[data-report-version]').length,2);d.querySelector('[data-qw-close]').click();assert.ok(d.querySelector('[data-report-fetch]'));assert.ok(!d.body.textContent.includes('转入 Auto-UT'));d.querySelector('[data-report-fetch]').click();await pause();assert.deepEqual(captured.versions,config.versions);assert.equal(d.querySelectorAll('[data-report-select]').length,2);const first=d.querySelector('[data-report-select]');first.checked=false;first.dispatchEvent(new dom.window.Event('change'));d.querySelector('[data-auto-ut-start]').click();await pause();assert.ok(calls.includes('/api/auto-ut/reports/r1/tasks'));}finally{dom.window.close();}
});
test('同仓库不同版本的任务进度都显示，CSV 入口保留',async()=>{
 const dom=page(path=>path==='/api/auto-ut/tasks'?['R27C10','R27C00'].map((reportVersion,i)=>({id:String(i),repository:'Demo',reportVersion,status:'RESOLVED',nextStage:'DONE',progress:100,workspaceRoot:'/tmp',repairBranch:'repair',message:'完成'})):undefined);
 try{const d=open(dom,'auto-ut');await pause();d.querySelector('[data-qw-auto-tab="tasks"]').click();assert.equal(d.querySelectorAll('[data-auto-ut-task]').length,2);d.querySelector('[data-report-source="csv"]').click();assert.equal(d.querySelector('.auto-ut-file').hidden,false);assert.ok(d.querySelector('#auto-ut-report'));}finally{dom.window.close();}
});
test('质量检查独立查询多版本三种类型，结果区区分空数据',async()=>{
 let body;const dom=page((path,o)=>{if(path==='/api/quality/jobs'&&o?.method==='POST'){body=JSON.parse(o.body);return{id:'q1',status:'SUCCEEDED',createdAt:'now',input:body,parts:body.versions.map(version=>({version,kind:'ut',status:'EMPTY',message:'没有有效报告数据，不执行修复',columns:[],rows:[]}))};}});
 try{const d=open(dom,'quality');await pause();d.querySelector('[data-q-fetch]').click();await pause();assert.deepEqual(body.versions,['R27C10','R27C00']);assert.deepEqual(body.kinds,['ut','api','static']);assert.match(d.body.textContent,/没有有效报告数据/);d.querySelector('[data-qw-drawer="export"]').click();assert.equal(d.querySelectorAll('a[href*="/csv?"]').length,2);}finally{dom.window.close();}
});

test('设置以抽屉呈现；取消恢复配置，保存持久化多版本映射',async()=>{
 let saved;const dom=page((path,o)=>{if(path==='/api/auto-ut/report-settings'&&o?.method==='PUT'){saved=JSON.parse(o.body);return{config:saved,nextRunAt:null};}});
 try{const d=open(dom,'auto-ut');await pause();assert.equal(d.querySelector('[data-q-connection]'),null);assert.equal(d.querySelector('#auto-ut-username'),null);assert.equal(d.querySelector('[data-report-version]'),null);
 d.querySelector('[data-qw-drawer="versions"]').click();let input=d.querySelector('[data-report-branch]');input.value='changed';input.dispatchEvent(new dom.window.Event('input'));d.querySelector('[data-qw-close]').click();assert.match(d.querySelector('.qw-version-chip').textContent,/release\/27/);
 d.querySelector('[data-qw-drawer="versions"]').click();input=d.querySelector('[data-report-branch]');input.value='release/new';input.dispatchEvent(new dom.window.Event('input'));d.querySelector('[data-qw-save]').click();await pause();assert.equal(saved.versions[0].baseBranch,'release/new');assert.equal(d.querySelector('[role=dialog]'),null);assert.match(d.querySelector('.qw-version-chip').textContent,/release\/new/);
 }finally{dom.window.close();}
});
test('轮询刷新保持输入焦点、光标和抽屉滚动；Escape 取消编辑',async()=>{
 const dom=page();try{const d=open(dom,'auto-ut');await pause();d.querySelector('[data-qw-drawer="execution"]').click();let input=d.querySelector('#auto-ut-username');input.focus();input.value='tester-edit';input.dispatchEvent(new dom.window.Event('input'));input.setSelectionRange(3,3);d.querySelector('.qw-drawer-body').scrollTop=77;dom.window.render(false);input=d.querySelector('#auto-ut-username');assert.equal(d.activeElement,input);assert.equal(input.value,'tester-edit');assert.equal(input.selectionStart,3);assert.equal(d.querySelector('.qw-drawer-body').scrollTop,77);d.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Escape'}));assert.equal(d.querySelector('[role=dialog]'),null);d.querySelector('[data-qw-drawer="execution"]').click();assert.equal(d.querySelector('#auto-ut-username').value,'tester');}finally{dom.window.close();}
});
test('多选版本控件保持展开；结果类型可直接切换',async()=>{
 const dom=page();try{const d=open(dom,'quality');await pause();const picker=d.querySelector('[data-qw-open="picker-versions"]');picker.open=true;const selected=d.querySelector('[data-qw-pick="versions"][value="R26C10"]');selected.checked=true;selected.dispatchEvent(new dom.window.Event('change'));assert.equal(d.querySelector('[data-qw-open="picker-versions"]').open,true);assert.match(d.querySelector('[data-qw-open="picker-versions"] summary').textContent,/3/);d.querySelector('[data-qw-tab="api"]').click();assert.equal(d.querySelector('[data-qw-tab="api"]').getAttribute('aria-pressed'),'true');}finally{dom.window.close();}
});

test('定时规则通过统一 API 保存，不改写手动报告配置',async()=>{
 let saved;const dom=page((path,o)=>{if(path==='/api/automation/schedules'&&o?.method==='POST'){saved=JSON.parse(o.body);return{...saved,id:'s1'};}});
 try{const d=open(dom,'auto-ut');await pause();d.querySelector('[data-schedule-new="auto-ut"]').click();assert.equal(d.querySelector('#sched-weekday').hidden,true);const freq=d.querySelector('[data-sched-time="frequency"]');freq.value='weekly';freq.dispatchEvent(new dom.window.Event('change'));assert.equal(d.querySelector('#sched-weekday').hidden,false);d.querySelector('[data-qw-save]').click();await pause();assert.equal(saved.timing.frequency,'weekly');assert.equal(saved.enabled,true);assert.deepEqual(saved.task.config.versions,config.versions);}finally{dom.window.close();}
});
test('质量表分页、筛选与行详情使用同一份结果',async()=>{
 const rows=Array.from({length:25},(_,i)=>({'代码仓':'Repo'+i,'PL组':'Access_智能驾舱组','语言':'Java','失败用例':1,'行覆盖率':.5,'行覆盖率目标':.8,'分支覆盖率':.4,'分支覆盖率目标':.7}));const dom=page((path,o)=>path==='/api/quality/jobs'&&o?.method==='POST'?{id:'q1',status:'SUCCEEDED',createdAt:'now',input:JSON.parse(o.body),parts:[{version:'R27C10',kind:'ut',status:'SUCCEEDED',message:'查询完成',rows,columns:Object.keys(rows[0])}]}:undefined);
 try{const d=open(dom,'quality');await pause();d.querySelector('[data-q-fetch]').click();await pause();assert.equal(d.querySelectorAll('.qw-table tbody tr').length,20);d.querySelector('[data-qw-pager="quality"][data-step="1"]').click();assert.equal(d.querySelectorAll('.qw-table tbody tr').length,5);d.querySelector('[data-qw-detail]').click();assert.match(d.querySelector('#qw-drawer-title').textContent,/Repo20/);d.querySelector('[data-qw-close]').click();const search=d.querySelector('#q-search');search.value='Repo24';search.dispatchEvent(new dom.window.Event('input'));assert.equal(d.querySelectorAll('.qw-table tbody tr').length,1);assert.match(d.querySelector('.qw-table tbody').textContent,/Repo24/);}finally{dom.window.close();}
});

test('固定导航、浏览器前进后退保留查询条件与滚动位置',async()=>{
 const dom=page();try{const w=dom.window,d=open(dom,'quality');await pause();let scroll=0;Object.defineProperty(w,'scrollY',{get:()=>scroll});w.scrollTo=(_x,y)=>{scroll=y;};const input=d.querySelector('[data-q-field="domain"]');input.value='Access_Custom';input.dispatchEvent(new w.Event('input'));w.scrollTo(0,320);d.querySelector('[data-automation-nav="auto-ut"]').click();await pause();assert.equal(w.location.hash,'#/automation/auto-ut');assert.equal(d.querySelector('.qw-topnav'),null);assert.equal(d.querySelector('.page-head h1').textContent,'UT 自动修复');w.history.back();await new Promise(r=>setTimeout(r,30));assert.equal(w.location.hash,'#/automation/quality');assert.equal(d.querySelector('[data-q-field="domain"]').value,'Access_Custom');assert.equal(w.scrollY,320);w.history.forward();await new Promise(r=>setTimeout(r,30));assert.equal(d.querySelector('.page-head h1').textContent,'UT 自动修复');}finally{dom.window.close();}
});
test('独立地址直接打开定时管理页，面包屑返回概览',async()=>{
 const dom=page(undefined,'http://localhost/#/automation/schedules');try{await pause();const d=dom.window.document;assert.equal(d.querySelector('.page-head h1').textContent,'定时任务');assert.equal(d.querySelector('[data-automation-nav="schedules"]').getAttribute('aria-current'),'page');d.querySelector('[data-automation-back]').click();assert.equal(dom.window.location.hash,'#/automation');assert.equal(d.querySelector('.page-head h1').textContent,'自动化工具');await pause();}finally{dom.window.close();}
});
test('质量检查创建计划自动带入范围，并可在统一页暂停与立即执行',async()=>{
 let records=[],created,patched,executed=false;const dom=page((path,o)=>{if(path==='/api/automation/schedules'&&o?.method==='POST'){created=JSON.parse(o.body);const s={...created,id:'s1',revision:1,nextRunAt:'2026-09-22T01:00:00Z',running:false,lastRun:null};records=[s];return s;}if(path==='/api/automation/schedules')return records;if(path==='/api/automation/schedules/s1'&&o?.method==='PATCH'){patched=JSON.parse(o.body);records[0]={...records[0],...patched,revision:2,nextRunAt:null};return records[0];}if(path==='/api/automation/schedules/s1/runs'&&o?.method==='POST'){executed=true;return{id:'r1'};}});
 try{const d=open(dom,'quality');await pause();d.querySelector('[data-schedule-new="quality"]').click();assert.equal(d.querySelector('[data-sched-quality="versions"]').value,'R27C10, R27C00');d.querySelector('[data-qw-save]').click();await pause();assert.equal(created.task.kind,'quality');assert.deepEqual(created.task.query.kinds,['ut','api','static']);d.querySelector('[data-automation-nav="schedules"]').click();await pause();assert.match(d.querySelector('.qw-table tbody').textContent,/每日质量检查/);d.querySelector('[data-schedule-toggle]').click();await pause();assert.equal(patched.enabled,false);assert.equal(patched.revision,1);d.querySelector('[data-schedule-run]').click();await pause();assert.equal(executed,true);}finally{dom.window.close();}
});
