/* Read-only cross-user reporting; existing workspace navigation stays intact. */
(()=>{
 const labels={'platform':'平台任务','auto-ut-task':'UT 治理','group-mr-entry':'群组 MR','quality-job':'质量检查','auto-ut-report-run':'UT 报告','build-task':'构建','deployment-task':'部署','automation-schedule-run':'定时执行'};
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=value=>value?new Date(value).toLocaleString():'—';
 let host;
 document.addEventListener('click',event=>{if(event.target.closest?.('[data-ops-admin]')&&window.opsAuth?.user?.isAdmin)void open(event.target);});
 async function open(trigger){
  if(host)return;
  host=document.createElement('div');host.id='ops-admin';const root=host.attachShadow({mode:'open'});
  root.innerHTML=`<style>:host{position:fixed;inset:0;z-index:10000;background:#17202c66;display:grid;place-items:center;padding:24px;font:14px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif;color:#20252b}*{box-sizing:border-box}.panel{background:#fff;border-radius:16px;width:min(1250px,100%);max-height:92vh;overflow:auto;padding:26px}header,.filters,.pager{display:flex;align-items:center;gap:12px;flex-wrap:wrap}header{justify-content:space-between}h2{margin:0}p{color:#78808b;margin:6px 0 18px}button,select{font:inherit;border:1px solid #dfe2e8;background:white;border-radius:7px;padding:7px 12px;color:inherit}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}button:focus-visible,select:focus-visible{outline:2px solid #5261cf}.table{overflow:auto;margin:14px 0 24px}table{border-collapse:collapse;width:100%;text-align:left;white-space:nowrap}th,td{border-bottom:1px solid #e7e9ed;padding:10px 12px}th{background:#f7f8fa;font-size:12px;color:#626b78}td.title{white-space:normal;min-width:180px;max-width:340px;overflow-wrap:anywhere}.error{color:#b95050}.pager{justify-content:flex-end}summary{cursor:pointer}dl{white-space:normal;overflow-wrap:anywhere;font-size:12px}dd{margin:0 0 6px;color:#697186}</style><section class="panel" role="dialog" aria-modal="true" aria-labelledby="admin-title"><header><h2 id="admin-title">用户管理</h2><div><button id="refresh">刷新</button> <button id="close">返回工作空间</button></div></header><p>查看所有用户的使用概况与任务记录 · 只读</p><div id="error" role="alert" class="error"></div><div id="users" class="table">正在读取用户…</div><div class="filters"><label>用户 <select id="account"></select></label><label>任务类型 <select id="kind"><option value="all">全部类型</option>${Object.entries(labels).map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select></label></div><div id="tasks" class="table"></div><div class="pager"><span id="page-info"></span><button id="prev">上一页</button><button id="next">下一页</button></div></section>`;
  document.body.append(host);let page=1,total=0,sequence=0,closed=false;const pageSize=30,controller=new AbortController();
  const el=id=>root.getElementById(id),close=()=>{closed=true;controller.abort();host?.remove();host=null;trigger?.focus();};
  el('close').onclick=close;el('close').focus();
  root.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();close();}if(event.key==='Tab'){const items=[...root.querySelectorAll('button:not(:disabled),select,summary')],first=items[0],last=items.at(-1);if(event.shiftKey&&root.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&root.activeElement===last){event.preventDefault();first?.focus();}}});
  async function get(url){const response=await fetch(url,{signal:controller.signal});const value=await response.json();if(!response.ok)throw Error(value.message||'读取失败');return value;}
  function paging(){el('page-info').textContent=`共 ${total} 条 · 第 ${page} / ${Math.max(1,Math.ceil(total/pageSize))} 页`;el('prev').disabled=page<=1;el('next').disabled=page*pageSize>=total;}
  async function tasks(){const request=++sequence;el('error').textContent='';el('tasks').textContent='正在读取任务…';el('prev').disabled=el('next').disabled=true;
   try{const query=new URLSearchParams({account:el('account').value,kind:el('kind').value,page:String(page),pageSize:String(pageSize)});if(!query.get('account')){el('tasks').textContent='暂无用户';total=0;paging();return;}const data=await get('/api/admin/tasks?'+query);if(closed||request!==sequence)return;total=data.total;el('tasks').innerHTML=data.items.length?`<table><thead><tr><th>任务类型</th><th>任务</th><th>状态 / 阶段</th><th>进度</th><th>更新时间</th><th>详情</th></tr></thead><tbody>${data.items.map(item=>`<tr><td>${esc(labels[item.kind]||item.kind)}</td><td class="title">${esc(item.title)}</td><td>${esc(item.status)}${item.stage?' / '+esc(item.stage):''}</td><td>${item.progress===null?'—':esc(item.progress)+'%'}</td><td>${esc(date(item.updatedAt))}</td><td><details><summary>查看</summary><dl><dt>任务 ID</dt><dd>${esc(item.id)}</dd><dt>版本 / 分支</dt><dd>${esc(item.version||'—')} / ${esc(item.branch||'—')}</dd><dt>创建时间</dt><dd>${esc(date(item.createdAt))}</dd></dl></details></td></tr>`).join('')}</tbody></table>`:'暂无任务记录';paging();}catch(error){if(closed||request!==sequence)return;el('error').textContent=error.message;el('tasks').textContent='任务读取失败，请刷新重试。';}}
  async function refresh(){el('refresh').disabled=true;el('users').textContent='正在读取用户…';try{const data=await get('/api/admin/users');if(closed)return;const selected=el('account').value;el('account').innerHTML=data.users.map(user=>`<option value="${esc(user.account)}">${esc(user.account)}</option>`).join('');if(data.users.some(user=>user.account===selected))el('account').value=selected;el('users').innerHTML=`<table><thead><tr><th>账号</th><th>权限 / 状态</th><th>登录次数</th><th>最近登录</th><th>最近任务活动</th><th>环境 / 计划</th><th>任务总数</th><th></th></tr></thead><tbody>${data.users.map(user=>`<tr><td>${esc(user.account)}</td><td>${user.isAdmin?'管理员':'普通用户'} / ${user.allowed?'已授权':'已停用'}</td><td>${esc(user.loginCount)}</td><td>${esc(date(user.lastLoginAt))}</td><td>${esc(date(user.lastActivityAt))}</td><td>${esc(user.environments??'—')} / ${esc(user.schedules??'—')}</td><td>${esc(user.tasks??'—')}${user.error?'<span class="error"> '+esc(user.error)+'</span>':''}</td><td><button data-user="${esc(user.account)}">查看任务</button></td></tr>`).join('')}</tbody></table>`;page=1;await tasks();}catch(error){if(!closed){el('error').textContent=error.message;el('users').textContent='用户读取失败，请刷新重试。';el('tasks').textContent='';}}finally{el('refresh').disabled=false;}}
  el('users').onclick=event=>{const button=event.target.closest('[data-user]');if(button){el('account').value=button.dataset.user;page=1;void tasks();}};
  el('account').onchange=el('kind').onchange=()=>{page=1;void tasks();};el('prev').onclick=()=>{page--;void tasks();};el('next').onclick=()=>{page++;void tasks();};el('refresh').onclick=()=>void refresh();await refresh();
 }
})();
