import {readUtXml,decideGovernance,verifiedChanges,utRegressionPassed,governanceMetrics,type Governance,type GovernanceRecord,type UtEvidence} from './governance.js';
import type {UnifiedSchedules} from '../automation/schedules.js';
import {randomUUID} from 'node:crypto';
import {readFile,writeFile,mkdir,stat,readdir,unlink,rm} from 'node:fs/promises';
import {resolve,join,relative} from 'node:path';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import multipart from '@fastify/multipart';
import {parse} from 'csv-parse/sync';
import {XMLParser} from 'fast-xml-parser';
import {z} from 'zod';
import type {TaskStore} from '../../platform/store.js';
import {noFileLogs} from '../../infrastructure/file-logs.js';
import type {LogSink} from '../../infrastructure/file-logs.js';
import {runProcess} from '../../infrastructure/process.js';
import {durableSse} from '../../infrastructure/sse.js';
import {browse} from '../workspace/directories.js';

type Mode='MANUAL'|'AUTOMATIC';type Stage='PREPARE'|'BASELINE'|'REPAIR'|'VERIFY'|'PUBLISH'|'DONE';
type Status='DISCOVERED'|'WAITING_CONFIRMATION'|'WAITING_REPOSITORY'|'PREPARING'|'BASELINE_RUNNING'|'REPAIRING'|'VERIFYING'|'RETRY_PENDING'|'WAITING_EXTERNAL'|'PR_CREATING'|'RESOLVED';
interface History{time:string;status:Status;message:string}interface LiveEvent{sequence:number;time:string;type:string;content:string;toolCallId:string;toolName:string;error:boolean;replace:boolean}
interface ReportItem{repository:string;failedTests:number;lineCoverage:number;lineGoal:number;branchCoverage:number;branchGoal:number}
interface Repository{name:string;url:string;testCommand:string[];verificationCommand:string[];coverageReport:string;customized:boolean;updatedAt:string|null}
export interface AutoUtTask{governance?:Governance;id:string;reportVersion?:string;sourceReportId?:string;repository:string;username:string;ticket:string;baseBranch:string;repairBranch:string;reportedFailedTests:number;lineGoal:number;branchGoal:number;workspaceRoot:string;workspacePath?:string;executionMode:Mode;status:Status;nextStage:Stage;progress:number;attempts:number;message:string;pullRequestUrl:string;createdAt:string;updatedAt:string;history:History[];liveEvents:LiveEvent[];liveSequence:number}
export interface Schedule{reportFileName:string;report:string;username:string;ticket:string;baseBranch:string;workspaceRoot:string;dailyTime:string;lastTriggeredOn:string|null;updatedAt:string}
const identity=z.string().regex(/^[A-Za-z0-9._-]+$/);const branch=z.string().trim().min(1).max(200).regex(/^[A-Za-z0-9][A-Za-z0-9._/-]*$/).refine(v=>!v.includes('..')&&!v.includes('//')&&!v.endsWith('/')&&!v.endsWith('.'));
const settings={language:'Java',plGroup:'Access_智能驾舱组',logDirectory:resolve(process.env.PLATFORM_LOG_DIR?.trim()||'data/logs','auto-ut','details'),piCommand:'pi',thinkingLevel:'medium',piTimeoutMs:30*60_000,maxAttempts:3,
 forbiddenMarkers:['@Disabled','@Ignore'],codehub:'codehub-cli',createMr:true,reviewers:process.env.AUTO_UT_CODEHUB_REVIEWERS?.trim()??'',approvers:process.env.AUTO_UT_CODEHUB_APPROVERS?.trim()??'',assignees:process.env.AUTO_UT_CODEHUB_ASSIGNEES?.trim()??''};
const testCommand=['mvn','-B','-ntp','-s','.ci/settings.xml','clean','test','-Djacoco.skip=true'];const verificationCommand=[...testCommand];
const stageInfo:Record<Stage,{status:Status;progress:number;message:string}>={PREPARE:{status:'PREPARING',progress:10,message:'正在准备独立 Git 工作区。'},BASELINE:{status:'BASELINE_RUNNING',progress:25,message:'正在执行基线 UT。'},REPAIR:{status:'REPAIRING',progress:45,message:'正在执行 Pi 修复。'},VERIFY:{status:'VERIFYING',progress:70,message:'正在执行完整验证。'},PUBLISH:{status:'PR_CREATING',progress:90,message:'正在提交并创建 CodeHub MR。'},DONE:{status:'RESOLVED',progress:100,message:'任务已完成。'}};

export interface CodecovReport{tests:number;failures:number;errors:number;skipped:number;line:number;branch:number}
const normalized=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]/g,'');
function numberValue(value:unknown):number|undefined{if(typeof value==='number'&&Number.isFinite(value))return value;if(typeof value==='string'){const parsed=Number(value.trim().replace(/%$/,''));if(Number.isFinite(parsed))return parsed;}return;}
function findNumber(value:unknown,aliases:Set<string>):number|undefined{if(!value||typeof value!=='object')return;for(const[key,item]of Object.entries(value)){if(aliases.has(normalized(key))){const found=numberValue(item);if(found!==undefined)return found;}}for(const item of Object.values(value)){const found=findNumber(item,aliases);if(found!==undefined)return found;}return;}
function testTotal(value:unknown):number|undefined{const direct=findNumber(value,new Set(['tests','totaltests','teststotal','testsrun','testcount']));if(direct!==undefined)return direct;const visit=(node:unknown):number|undefined=>{if(!node||typeof node!=='object')return;for(const[key,item]of Object.entries(node)){if(['tests','testresults','testsummary'].includes(normalized(key))&&item&&typeof item==='object'){const found=findNumber(item,new Set(['total','count','run','executed']));if(found!==undefined)return found;}}for(const item of Object.values(node)){const found=visit(item);if(found!==undefined)return found;}return;};return visit(value);}
function coverageValue(value:unknown,kind:'line'|'branch'):number|undefined{
 const direct=findNumber(value,new Set([`${kind}coverage`,`${kind}coveragerate`,`${kind}rate`,`${kind}percent`,`${kind}percentage`]));if(direct!==undefined)return direct>1?direct/100:direct;
 const visit=(node:unknown):number|undefined=>{if(!node||typeof node!=='object')return;for(const[key,item]of Object.entries(node)){if(normalized(key)!==kind||!item||typeof item!=='object')continue;const explicit=findNumber(item,new Set(['coverage','coveragerate','rate','percent','percentage','value']));if(explicit!==undefined)return explicit>1?explicit/100:explicit;const covered=findNumber(item,new Set(['covered','coveredcount'])),total=findNumber(item,new Set(['total','count'])),missed=findNumber(item,new Set(['missed','uncovered','missedcount']));if(covered!==undefined&&(total!==undefined||missed!==undefined)){const denominator=total??covered+missed!;return denominator===0?1:covered/denominator;}}
  for(const item of Object.values(node)){const found=visit(item);if(found!==undefined)return found;}return;};return visit(value);
}
function jsonObjects(output:string):unknown[]{const result:unknown[]=[];let start=-1,depth=0,quoted=false,escaped=false;for(let index=0;index<output.length;index++){const char=output[index]!;if(start<0){if(char==='{'){start=index;depth=1;}continue;}if(quoted){if(escaped)escaped=false;else if(char==='\\')escaped=true;else if(char==='"')quoted=false;continue;}if(char==='"'){quoted=true;continue;}if(char==='{')depth++;else if(char==='}'&&--depth===0){try{result.push(JSON.parse(output.slice(start,index+1)));}catch{/* mixed log fragment */}start=-1;}}return result;}
export function parseCodecovReport(output:string):CodecovReport{let best:CodecovReport|undefined,bestScore=-1;for(const value of jsonObjects(output)){const tests=testTotal(value),failures=findNumber(value,new Set(['failures','failed','failedtests','testsfailed','failurecount'])),errors=findNumber(value,new Set(['errors','errortests','testerrors','errorcount'])),skipped=findNumber(value,new Set(['skipped','skip','ignored','skippedtests','skipcount'])),line=coverageValue(value,'line'),branch=coverageValue(value,'branch');const score=[tests,failures,errors,skipped,line,branch].filter(item=>item!==undefined).length;if(score>bestScore&&tests!==undefined&&line!==undefined&&branch!==undefined){best={tests:Math.trunc(tests),failures:Math.trunc(failures??0),errors:Math.trunc(errors??0),skipped:Math.trunc(skipped??0),line,branch};bestScore=score;}}
 if(!best)throw new Error('无法从 codecovcli 输出中读取测试与覆盖率 JSON。');return best;
}

function textValue(value:unknown):string{if(typeof value==='string'||typeof value==='number')return String(value);if(value&&typeof value==='object'){const object=value as Record<string,unknown>;return textValue(object['#text']??object['@_message']??'');}return'';}
export function surefireFailureDetails(content:string):string[]{const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',allowBooleanAttributes:true,trimValues:false});const xml=parser.parse(content) as Record<string,unknown>;const array=<T>(value:T|T[]|undefined):T[]=>value===undefined?[]:Array.isArray(value)?value:[value];const root=(xml.testsuites??{}) as Record<string,unknown>,suites=array((xml.testsuite??root.testsuite) as Record<string,unknown>|Record<string,unknown>[]|undefined);const details:string[]=[];for(const suite of suites)for(const testcase of array(suite.testcase as Record<string,unknown>|Record<string,unknown>[]|undefined)){for(const kind of ['failure','error'] as const)for(const failure of array(testcase[kind])){const object=failure&&typeof failure==='object'?failure as Record<string,unknown>:{};const title=[textValue(testcase['@_classname']),textValue(testcase['@_name'])].filter(Boolean).join('#')||'未知测试用例';const type=textValue(object['@_type']),message=textValue(object['@_message']),stack=textValue(object['#text']??failure).trim();details.push([`${kind.toUpperCase()} ${title}`,type&&`类型：${type}`,message&&`消息：${message}`,stack&&`堆栈：\n${stack.slice(0,12000)}`].filter(Boolean).join('\n'));}}return details;}

export function autoUtWorkspace(task:Pick<AutoUtTask,'workspaceRoot'|'repository'|'reportVersion'>){
 const root=resolve(task.workspaceRoot),version=task.reportVersion?.trim();if(version&&!/^[A-Za-z0-9._-]+$/.test(version))throw new Error('报告版本不能用于工作目录');
 const workspace=version?resolve(root,version,task.repository.toLowerCase()):resolve(root,task.repository.toLowerCase());
 if(relative(root,workspace).startsWith('..'))throw new Error('服务工作目录越界');return workspace;
}

export class AutoUtService{
 private readonly running=new Set<string>();private readonly deleting=new Set<string>();private timer:NodeJS.Timeout;
 constructor(private readonly store:TaskStore,private readonly logs:LogSink=noFileLogs,private readonly ownScheduler=true){for(const task of this.tasks().filter(t=>['DISCOVERED','PREPARING','BASELINE_RUNNING','REPAIRING','VERIFYING','PR_CREATING'].includes(t.status))){this.change(task,'WAITING_EXTERNAL','服务重启，原执行进程已中断，请重试当前阶段。');this.save(task);}
  this.timer=setInterval(()=>{if(this.ownScheduler)void this.triggerDue();},30_000);this.timer.unref();}
 close(){clearInterval(this.timer);}
 private save(task:AutoUtTask){task.updatedAt=new Date().toISOString();this.store.putRecord('auto-ut-task',task.id,task,task.createdAt);if(task.governance){const {id,repository,reportVersion,baseBranch,status,message,createdAt,updatedAt,pullRequestUrl}=task;const governance={...task.governance,baseline:undefined,verified:undefined};this.store.putRecord('auto-ut-governance',id,{id,repository,reportVersion,baseBranch,status,message,createdAt,updatedAt,pullRequestUrl,governance},createdAt);}}
 governanceRecords(){return this.store.records<GovernanceRecord>('auto-ut-governance');}
 governanceSummary(version='',days=0){const cutoff=days?Date.now()-days*86400000:0;const records=this.governanceRecords().filter(r=>(!version||r.reportVersion===version)&&Date.parse(r.createdAt)>=cutoff);return{metrics:governanceMetrics(records),records};}
 resolveMr(id:string,state:'MERGED'|'CLOSED'){const record=this.store.getRecord<GovernanceRecord>('auto-ut-governance',id);if(!record?.pullRequestUrl||record.status!=='RESOLVED')throw Object.assign(new Error('没有待确认的已完成 MR'),{statusCode:409});record.governance.mrState=state;record.updatedAt=new Date().toISOString();this.store.putRecord('auto-ut-governance',id,record,record.createdAt);const task=this.store.getRecord<AutoUtTask>('auto-ut-task',id);if(task?.governance){task.governance.mrState=state;this.save(task);}return record;}
 blocksRepository(repository:string,version:string,baseBranch:string){return this.tasks().some(t=>t.repository.toLowerCase()===repository.toLowerCase()&&(t.reportVersion===version||!t.reportVersion&&t.baseBranch===baseBranch)&&t.status!=='RESOLVED')||this.governanceRecords().some(r=>r.repository.toLowerCase()===repository.toLowerCase()&&(r.reportVersion===version||!r.reportVersion&&r.baseBranch===baseBranch)&&r.governance.mrState==='PENDING')||this.tasks().some(t=>!t.governance&&t.pullRequestUrl&&t.repository.toLowerCase()===repository.toLowerCase()&&t.reportVersion===version);}
 private change(task:AutoUtTask,status:Status,message:string){task.status=status;task.message=message;task.updatedAt=new Date().toISOString();const event={time:task.updatedAt,status,message};task.history.push(event);this.logs.task('auto-ut',task.id,{kind:'history',...event});}
 private emit(task:AutoUtTask,type:string,content='',toolCallId='',toolName='',error=false,replace=false){const event={sequence:++task.liveSequence,time:new Date().toISOString(),type,content,toolCallId,toolName,error,replace};
  if(replace&&toolCallId)task.liveEvents=task.liveEvents.filter(e=>!(e.replace&&e.type===type&&e.toolCallId===toolCallId));task.liveEvents.push(event);this.logs.task('auto-ut',task.id,{kind:'live',...event});if(task.liveEvents.length>10000)task.liveEvents.shift();this.save(task);return event;}
 private taskView(task:AutoUtTask){task.workspacePath=autoUtWorkspace(task);return task;}
 tasks(){return this.store.records<AutoUtTask>('auto-ut-task').map(task=>this.taskView(task));}get(id:string){const task=this.store.getRecord<AutoUtTask>('auto-ut-task',id);if(!task)throw Object.assign(new Error('Auto-UT 任务不存在'),{statusCode:404});return this.taskView(task);}
 async deleteTask(id:string){const task=this.get(id);if(this.running.has(id)||this.deleting.has(id))throw Object.assign(new Error('正在执行的 UT 修复任务不能删除'),{statusCode:409});const workspace=autoUtWorkspace(task),shared=this.tasks().find(other=>other.id!==id&&autoUtWorkspace(other)===workspace&&!this.terminalStatus(other.status));if(shared)throw Object.assign(new Error(`工作目录正被未完成任务 ${shared.id} 使用，不能删除`),{statusCode:409});this.deleting.add(id);try{const root=resolve(task.workspaceRoot),boundary=relative(root,workspace);if(!boundary||boundary.startsWith('..')||resolve(root,boundary)!==workspace)throw Object.assign(new Error('任务工作目录不合法，拒绝清理'),{statusCode:409});await rm(workspace,{recursive:true,force:true});await rm(join(settings.logDirectory,id),{recursive:true,force:true});this.store.deleteRecord('auto-ut-task',id);return{id,workspace,workspaceDeleted:true};}catch(error){if(error instanceof Error&&'statusCode' in error)throw error;throw Object.assign(new Error(`UT 修复工作目录清理失败：${error instanceof Error?error.message:'未知错误'}`),{statusCode:409});}finally{this.deleting.delete(id);}}
 async cleanup(retentionDays:number,now=new Date()){const days=z.number().int().min(1).max(365).parse(retentionDays),cutoff=now.getTime()-days*86_400_000;const candidates=this.tasks().filter(task=>Date.parse(task.updatedAt)<cutoff&&['RESOLVED','RETRY_PENDING','WAITING_EXTERNAL','WAITING_REPOSITORY'].includes(task.status));const deleted:string[]=[],failed:Array<{id:string;message:string}>=[];for(const task of candidates)try{await this.deleteTask(task.id);deleted.push(task.id);}catch(error){failed.push({id:task.id,message:error instanceof Error?error.message:'清理失败'});}return{retentionDays,cutoff:new Date(cutoff).toISOString(),deleted,failed};}
 private terminalStatus(status:Status){return!['DISCOVERED','PREPARING','BASELINE_RUNNING','REPAIRING','VERIFYING','PR_CREATING','WAITING_CONFIRMATION','WAITING_EXTERNAL'].includes(status);}
 private repository(name:string):Repository|undefined{if(!/^[A-Za-z0-9._-]+$/.test(name))return;const key=name.toLowerCase();const custom=this.store.getRecord<{url:string;updatedAt:string}>('auto-ut-repository',key);return{name:key,url:custom?.url??`ssh://git@szv-y.codehub.huawei.com:2222/MAE-M/Access/${name}.git`,testCommand,verificationCommand,coverageReport:'.codecovcli/report/result.json',customized:!!custom,updatedAt:custom?.updatedAt??null};}
 saveRepository(name:string,url:string){if(!/^[A-Za-z0-9._-]+$/.test(name))throw Object.assign(new Error('代码仓名称格式无效'),{statusCode:400});let parsed:URL;try{parsed=new URL(url.trim());}catch{throw Object.assign(new Error('请输入有效的 CodeHub clone URL'),{statusCode:400});}
  if(!['ssh:','https:','http:'].includes(parsed.protocol)||!parsed.hostname.toLowerCase().endsWith('.codehub.huawei.com')||!parsed.pathname.endsWith('.git'))throw Object.assign(new Error('请输入有效的 CodeHub clone URL'),{statusCode:400});
  const updatedAt=new Date().toISOString();this.store.putRecord('auto-ut-repository',name.toLowerCase(),{url:url.trim(),updatedAt});return{repository:name,url:url.trim(),customized:true,updatedAt};}
 parseReport(report:Buffer):ReportItem[]{if(!report.length)throw Object.assign(new Error('CSV 报告不能为空'),{statusCode:400});let rows:Record<string,string>[];try{rows=parse(report,{bom:true,columns:true,skip_empty_lines:true,trim:true});}catch(error){throw Object.assign(new Error(`CSV 报告格式无效：${error instanceof Error?error.message:'解析失败'}`),{statusCode:400});}
  const required=['代码仓','语言','PL组','失败用例','行覆盖率','行覆盖率目标','分支覆盖率','分支覆盖率目标'];const columns=rows[0]?Object.keys(rows[0]):[];const missing=required.filter(c=>!columns.includes(c));if(missing.length)throw Object.assign(new Error(`CSV 缺少必要列：${missing.sort().join('、')}`),{statusCode:400});
  const percent=(v:string)=>{const t=(v??'').trim();return!t?NaN:t.endsWith('%')?Number(t.slice(0,-1))/100:Number(t);};const items=new Map<string,ReportItem>();for(const row of rows){const repository=row['代码仓']??'';const item={repository,failedTests:Math.trunc(Number(row['失败用例']||0)),lineCoverage:percent(row['行覆盖率']??''),lineGoal:percent(row['行覆盖率目标']??''),branchCoverage:percent(row['分支覆盖率']??''),branchGoal:percent(row['分支覆盖率目标']??'')};
    if(repository&&row['语言']?.toLowerCase()===settings.language.toLowerCase()&&row['PL组']===settings.plGroup&&(item.failedTests>0||item.lineCoverage<item.lineGoal||item.branchCoverage<item.branchGoal))items.set(repository.toLowerCase(),item);}return[...items.values()];}
 scan(report:Buffer,username:string,ticket:string,baseBranch:string){this.validate(username,ticket,baseBranch);return this.parseReport(report).map(item=>{const repository=this.repository(item.repository);return{...item,configured:!!repository,repositoryUrl:repository?.url??'',repositoryCustomized:repository?.customized??false,baseBranch,repairBranch:repository?`${baseBranch}_${username}_${ticket}`:''};});}
 async start(report:Buffer,username:string,ticket:string,baseBranch:string,workspaceRoot:string,executionMode:Mode,source?:{version:string;reportId:string;maxClasses?:number;reportAt?:string}){this.validate(username,ticket,baseBranch);const root=await this.workspace(workspaceRoot);return this.parseReport(report).map(item=>{if(this.blocksRepository(item.repository,source?.version??'',baseBranch))throw Object.assign(new Error('已有未完成任务或待确认 MR，请先处理原任务。'),{statusCode:409});const repository=this.repository(item.repository);const now=new Date().toISOString();const task:AutoUtTask={governance:{mode:'NONE',coverageLow:(Number.isFinite(item.lineCoverage)&&Number.isFinite(item.lineGoal)&&item.lineCoverage<item.lineGoal)||(Number.isFinite(item.branchCoverage)&&Number.isFinite(item.branchGoal)&&item.branchCoverage<item.branchGoal),maxClasses:source?.maxClasses??5,...(source?.reportAt?{reportAt:source.reportAt}:{})},id:randomUUID(),...(source?{reportVersion:source.version,sourceReportId:source.reportId}:{}),repository:item.repository,username,ticket,baseBranch,repairBranch:repository?`${baseBranch}_${username}_${ticket}${source?'_'+source.version:''}_${randomUUID().slice(0,8)}`:'',reportedFailedTests:item.failedTests,lineGoal:item.lineGoal,branchGoal:item.branchGoal,workspaceRoot:root,executionMode,status:'DISCOVERED',nextStage:'PREPARE',progress:0,attempts:0,message:'已发现待修复任务',pullRequestUrl:'',createdAt:now,updatedAt:now,history:[],liveEvents:[],liveSequence:0};task.workspacePath=autoUtWorkspace(task);
    this.change(task,'DISCOVERED','已发现待修复任务');if(!repository)this.change(task,'WAITING_REPOSITORY','代码仓未配置，任务未执行。');this.save(task);if(repository)this.schedule(task,repository);return task;});}
 continue(id:string){const task=this.get(id);if(this.deleting.has(id))throw Object.assign(new Error('任务正在删除，不能继续执行'),{statusCode:409});const repository=this.repository(task.repository);if(!repository)throw Object.assign(new Error('代码仓未配置，任务无法继续。'),{statusCode:409});if(!(task.executionMode==='MANUAL'&&task.status==='WAITING_CONFIRMATION')&&task.status!=='WAITING_EXTERNAL'&&task.status!=='RETRY_PENDING')throw Object.assign(new Error('当前任务不处于可继续或重试的阶段。'),{statusCode:409});if(task.status==='RETRY_PENDING')task.attempts=0;this.change(task,'DISCOVERED',`下一阶段已进入执行队列：${stageInfo[task.nextStage].message}`);this.save(task);this.schedule(task,repository);return task;}
 events(id:string,after:number){return this.get(id).liveEvents.filter(e=>e.sequence>after);}terminal(id:string){return this.terminalStatus(this.get(id).status);}
 private validate(username:string,ticket:string,baseBranch:string){identity.parse(username);identity.parse(ticket);branch.parse(baseBranch);}
 private async workspace(value:string){if(!value?.trim())throw Object.assign(new Error('请选择工作目录'),{statusCode:400});const root=resolve(value),probe=join(root,`.container-ops-kit-${randomUUID()}.probe`);try{const info=await stat(root);if(!info.isDirectory())throw new Error();await writeFile(probe,'',{flag:'wx'});await unlink(probe);}catch{await unlink(probe).catch(()=>{});throw Object.assign(new Error(`工作目录不存在或不可写：${root}`),{statusCode:400});}return root;}
 private schedule(task:AutoUtTask,repository:Repository){if(this.running.has(task.id)||this.deleting.has(task.id))return;this.running.add(task.id);void this.execute(task,repository).finally(()=>this.running.delete(task.id));}
 private claim(task:AutoUtTask){if(task.nextStage==='DONE'||!['DISCOVERED','WAITING_CONFIRMATION'].includes(task.status))return false;const info=stageInfo[task.nextStage];if(task.nextStage==='REPAIR')task.attempts++;task.progress=Math.max(task.progress,info.progress);this.change(task,info.status,task.nextStage==='REPAIR'&&task.governance?.mode==='SUPPLEMENT'?'正在补充测试。':info.message);this.save(task);return true;}
 private wait(task:AutoUtTask,nextStage:Stage,message:string,progress:number){task.nextStage=nextStage;task.progress=Math.max(task.progress,progress);this.change(task,'WAITING_CONFIRMATION',message);this.save(task);}
 private async execute(task:AutoUtTask,repository:Repository){const workspace=autoUtWorkspace(task);task.governance??={mode:'NONE',coverageLow:false,maxClasses:5};task.governance.startedAt??=new Date().toISOString();this.save(task);
  try{do{const stage=task.nextStage;if(!this.claim(task))return;if(stage==='PREPARE'){await this.prepare(task,repository,workspace);this.wait(task,'BASELINE',`工作区准备完成：${workspace}`,20);}else if(stage==='BASELINE'){const evidence=await this.baseline(task,repository,workspace);this.change(task,task.status,`基线 UT：共 ${evidence.tests}，失败 ${evidence.failures+evidence.errors}，跳过 ${evidence.skipped}`);task.governance.baseline=evidence;task.governance.mode=decideGovernance(evidence,task.governance.coverageLow);
    if(task.governance.mode==='NONE')this.completeWithoutChanges(task,'实际 UT 全部通过，无需修复。');
    else{await this.checkoutBranch(task,workspace);if(task.governance.mode==='SUPPLEMENT')await this.selectTargets(task,workspace);
      if(task.governance.mode==='SUPPLEMENT'&&!task.governance.targets?.length)this.completeWithoutChanges(task,'实际 UT 通过，未找到适合补充测试的候选类。');
      else this.wait(task,'REPAIR',task.governance.mode==='REPAIR'?'已按实际失败用例进入修复。':'实际 UT 通过，跳过修复并补充测试。',35);}
    }else if(stage==='REPAIR')await this.repair(task,workspace);else if(stage==='VERIFY')await this.verify(task,repository,workspace);else if(stage==='PUBLISH')await this.publish(task,workspace);this.save(task);}while(task.executionMode==='AUTOMATIC'&&task.status==='WAITING_CONFIRMATION');}
  catch(error){this.change(task,'WAITING_EXTERNAL',error instanceof Error?error.message:'Auto-UT 执行异常');this.save(task);}}
 private async command(task:AutoUtTask,command:string[],directory:string,timeout:number,label:string,required=true){const id=randomUUID();this.emit(task,'operation_start',label,id,command.join(' '));const safe=label.replace(/[^\p{L}\p{N}._-]/gu,'_');try{const result=await runProcess(command,directory,timeout,join(settings.logDirectory,task.id,`${safe}.log`));this.emit(task,'operation_end',label,id,'',result.exitCode!==0);if(required&&result.exitCode!==0)throw new Error(`${label}失败，退出码 ${result.exitCode}：${result.output.slice(0,2000)}`);return result;}catch(error){this.emit(task,'operation_end',label,id,'',true);throw error;}}
 private async prepare(task:AutoUtTask,repository:Repository,workspace:string){await mkdir(resolve(workspace,'..'),{recursive:true});const exists=await stat(workspace).then(()=>true).catch(()=>false);if(exists){const git=await this.command(task,['git','rev-parse','--git-dir'],workspace,120000,'检查Git仓库');if(git.exitCode!==0)throw new Error(`工作目录不是 Git 仓库：${workspace}`);const origin=(await this.command(task,['git','remote','get-url','origin'],workspace,120000,'检查远端')).output.trim();if(origin.replace(/\/+$/,'').toLowerCase()!==repository.url.replace(/\/+$/,'').toLowerCase())throw new Error(`工作目录的 origin 与配置不一致：${workspace}`);if((await this.command(task,['git','status','--porcelain'],workspace,120000,'准备状态')).output.trim())throw new Error(`工作目录存在未提交修改，请先处理：${workspace}`);await this.command(task,['git','fetch','origin'],workspace,600000,'拉取仓库');}else await this.command(task,['git','clone','--branch',task.baseBranch,repository.url,workspace],resolve(workspace,'..'),600000,'克隆仓库');
  await this.command(task,['git','checkout',task.baseBranch],workspace,120000,'检出基础分支');await this.command(task,['git','pull','--ff-only','origin',task.baseBranch],workspace,600000,'更新基础分支');}
 private async baseline(task:AutoUtTask,repository:Repository,workspace:string){return(await this.testEvidence(task,repository.testCommand,workspace,'核验实际UT')).evidence;}
 private completeWithoutChanges(task:AutoUtTask,message:string){task.nextStage='DONE';task.progress=100;if(task.governance)task.governance.completedAt=new Date().toISOString();this.change(task,'RESOLVED',message);}
 private async testEvidence(task:AutoUtTask,command:string[],workspace:string,label:string){
  for(const file of(await this.files(workspace)).filter(p=>p.replaceAll('\\','/').includes('/target/surefire-reports/TEST-')&&p.endsWith('.xml')))await unlink(file);
  const result=await this.command(task,command,workspace,1800000,label,false);
  const evidence=await this.readSurefire(workspace);
  if(!evidence.tests)throw new Error('核验受阻：未执行任何 UT。');
  if(/org[/.]jacoco[/.]agent|Could not resolve dependencies|COMPILATION ERROR|Non-resolvable parent POM/.test(evidence.details+'\n'+result.output)||result.exitCode!==0&&!evidence.failedIds.length)throw new Error('核验受阻：构建、依赖或运行环境异常，请查看 '+label+' 日志。');
  return{evidence,exitCode:result.exitCode};
 }
 private async selectTargets(task:AutoUtTask,workspace:string){
  const files=await this.files(workspace),tests=files.filter(p=>p.replaceAll('\\','/').includes('/src/test/')&&p.endsWith('.java'));
  const texts=await Promise.all(tests.map(p=>readFile(p,'utf8'))),candidates:string[]=[];
  const sources=files.filter(p=>p.replaceAll('\\','/').includes('/src/main/java/')&&p.endsWith('.java')).sort();
  for(const file of sources){const name=file.split(/[\\\\/]/).at(-1)!.slice(0,-5);if(/(?:Dto|DTO|Vo|VO|Config|Configuration|Exception|Entity|Constants)$/.test(name)||texts.some(text=>new RegExp('\\b'+name+'\\b').test(text)))continue;
   const text=await readFile(file,'utf8');if(!/\bclass\s+/.test(text)||!/(?:if|switch|return|throw)\s*[(\s]/.test(text)||/@Generated/.test(text))continue;
   candidates.push(relative(workspace,file).replaceAll('\\','/'));if(candidates.length>=task.governance!.maxClasses)break;
  }task.governance!.targets=candidates;this.save(task);
 }
 private async checkoutBranch(task:AutoUtTask,workspace:string){const local=await this.command(task,['git','show-ref','--verify','--quiet',`refs/heads/${task.repairBranch}`],workspace,120000,'查询本地修复分支',false);if(local.exitCode===0){await this.command(task,['git','checkout',task.repairBranch],workspace,120000,'复用本地修复分支');return;}const remote=await this.command(task,['git','ls-remote','--exit-code','--heads','origin',task.repairBranch],workspace,120000,'查询远端修复分支',false);await this.command(task,remote.exitCode===0?['git','checkout','-B',task.repairBranch,`origin/${task.repairBranch}`]:['git','checkout','-b',task.repairBranch],workspace,120000,remote.exitCode===0?'复用远端修复分支':'创建修复分支');}
 private async repair(task:AutoUtTask,workspace:string){if(task.governance?.mode==='SUPPLEMENT'){await this.supplement(task,workspace);return;}const evidence=await this.readSurefire(workspace);const dir=join(settings.logDirectory,task.id);await mkdir(dir,{recursive:true});const prompt=join(dir,`第${task.attempts}轮提示词.md`);await writeFile(prompt,[
  '修复实际执行失败的 Java 单元测试。',
  '只能修改或新增 src/test 下的文件。禁止修改生产代码、构建配置，禁止删除测试、禁用测试、弱化断言。',
  '不要运行 codecovcli 或 JaCoCo。验证命令：'+testCommand.join(' '),
  '先运行针对性测试，完成后由平台执行全量回归。现有测试必须继续通过。',
  '只修复已复现的失败，不要求提升覆盖率。',
  '上次未通过原因：'+(task.governance?.lastFailure??'首次执行'),
  '先检查工作区现有 diff，保留已正确完成的修改，不要重复推翻。',
  '当前实际失败证据：',evidence.details||'当前没有失败用例。'
 ].join('\n'),'utf8');
  const result=await this.runPi(task,workspace,prompt);if(result.exitCode!==0){this.retry(task,`第 ${task.attempts} 轮 Pi 执行失败。`);return;}const guard=await this.inspect(task,workspace,`第${task.attempts}轮`);if(!guard.accepted){await this.command(task,['git','stash','push','--include-untracked','-m',`auto-ut拒绝-${task.id}-第${task.attempts}轮`],workspace,120000,'隔离违规修改');this.retry(task,`修改门禁未通过：${guard.violations.join('；')}`);return;}this.change(task,task.status,`修改门禁通过：${guard.changedFiles.length} 个测试文件`);this.wait(task,'VERIFY',`第 ${task.attempts} 轮修复完成，等待完整验证。`,60);}
 private retry(task:AutoUtTask,message:string){if(task.governance)task.governance.lastFailure=message;if(task.attempts>=settings.maxAttempts){task.nextStage='REPAIR';this.change(task,'RETRY_PENDING',`${message} 已达到最大修复轮次。`);}else this.wait(task,'REPAIR',`${message} 等待下一轮修复。`,60);}
 private async supplement(task:AutoUtTask,workspace:string){
  const g=task.governance!,baseline=g.baseline;if(!baseline)throw new Error('缺少实际基线，不能补充测试。');
  g.classResults??=[];
  const testFiles=async()=>(await this.files(workspace)).filter(p=>p.replaceAll('\\','/').includes('/src/test/'));
  for(const target of g.targets??[]){
   if(g.classResults.some(r=>r.target===target&&r.status==='PASSED'))continue;
   const snapshot=new Map(await Promise.all((await testFiles()).map(async path=>[path,await readFile(path)] as const)));
   const prompt=join(settings.logDirectory,task.id,'补充测试-'+g.classResults.length+'.md');
   await mkdir(join(settings.logDirectory,task.id),{recursive:true});
   await writeFile(prompt,[
    '为这个 Java 类补充有效单元测试：'+target,
    '只允许修改 src/test 下的测试文件。禁止修改生产代码和构建配置、删除测试、跳过测试或弱化断言。',
    '先阅读相关已有测试，保持项目现有框架与风格。覆盖正常路径、边界和异常路径，断言必须检查实际行为。',
    '只处理本次指定的类，保留工作区其他已经完成的修改。',
    '不要运行 codecovcli 或 JaCoCo。全量验证命令：'+testCommand.join(' '),
    '平台会核验新增用例是否执行通过。无法完成时明确说明原因。'
   ].join('\n'),'utf8');
   this.emit(task,'status','正在补充测试：'+target);
   try{
    const before=g.verified??baseline;
    const result=await this.runPi(task,workspace,prompt);if(result.exitCode!==0)throw new Error('Pi 执行未完成，退出码 '+result.exitCode);
    const guard=await this.inspect(task,workspace,'补测试');if(!guard.accepted)throw new Error(guard.violations.join('；'));
    const {evidence,exitCode}=await this.testEvidence(task,verificationCommand,workspace,'补测试回归-'+g.classResults.length);
    if(!utRegressionPassed(before,evidence,exitCode))throw new Error('新增测试未通过回归或改变了原有测试结果。');
    if(!verifiedChanges(before,evidence).addedIds.length)throw new Error('没有新增执行通过的用例。');
    g.verified=evidence;Object.assign(g,verifiedChanges(baseline,evidence));
    g.classResults=g.classResults.filter(r=>r.target!==target);
    g.classResults.push({target,status:'PASSED',message:'新增测试已通过回归'});
   }catch(error){
    // Restore only this class attempt's test edits; retain earlier successful work.
    for(const path of await testFiles())if(!snapshot.has(path))await unlink(path);
    for(const [path,content]of snapshot){await mkdir(resolve(path,'..'),{recursive:true});await writeFile(path,content);}
    const message=error instanceof Error?error.message:'补充测试失败';
    g.classResults=g.classResults.filter(r=>r.target!==target);
    g.classResults.push({target,status:'FAILED',message});this.emit(task,'status',target+'：'+message+'，已保留其他成功修改。');
    if(message.startsWith('核验受阻'))throw error;
   }this.save(task);
  }
  if(!(g.fixedIds?.length||g.addedIds?.length)){task.nextStage='REPAIR';this.change(task,'RETRY_PENDING','本批候选类均未新增有效测试，请查看失败原因。');return;}
  this.wait(task,'VERIFY','本批测试已处理，正在执行最终回归。',70);
 }
 private async verify(task:AutoUtTask,repository:Repository,workspace:string){
  const {evidence,exitCode}=await this.testEvidence(task,repository.verificationCommand,workspace,'完整UT回归');
  const governance=task.governance!,baseline=governance.baseline;
  if(!baseline)throw new Error('缺少实际基线，请重新创建治理任务。');
  governance.verified=evidence;
  if(!utRegressionPassed(baseline,evidence,exitCode)){this.retry(task,`回归未通过：失败 ${evidence.failures+evidence.errors}，跳过 ${evidence.skipped}；原有用例必须保留并通过。`);return;}
  Object.assign(governance,verifiedChanges(baseline,evidence));
  if(governance.mode==='REPAIR'&&governance.coverageLow){await this.selectTargets(task,workspace);if(governance.targets?.length){governance.mode='SUPPLEMENT';task.attempts=0;this.wait(task,'REPAIR','失败 UT 已修复，继续补充缺少的测试。',70);return;}}
  if(governance.mode==='SUPPLEMENT'&&!governance.addedIds?.length&&!governance.fixedIds?.length){this.retry(task,'全量回归通过，但没有新增执行通过的测试用例。');return;}
  this.wait(task,'PUBLISH','实际 UT 全量回归通过，准备创建 MR。',85);
 }
 private async inspect(task:AutoUtTask,workspace:string,prefix:string){const status=(await this.command(task,['git','-c','core.quotepath=false','status','--porcelain','--untracked-files=all'],workspace,120000,`${prefix}-修改状态`)).output;const changedFiles:string[]=[];const violations:string[]=[];for(const line of status.split(/\r?\n/)){if(line.length<4)continue;let path=line.slice(3).replaceAll('\\','/');if(path.includes(' -> '))path=path.slice(path.indexOf(' -> ')+4);if(!(path.startsWith('src/test/')||path.includes('/src/test/')))continue;changedFiles.push(path);if(line.slice(0,2).trim()==='D')violations.push(`禁止删除测试文件：${path}`);}if(!changedFiles.length)violations.push('Pi 未产生任何测试文件修改。');
  for(const path of changedFiles){const file=resolve(workspace,path);if(relative(workspace,file).startsWith('..'))continue;let text;try{text=await readFile(file,'utf8');}catch{continue;}const original=await this.command(task,['git','show',`HEAD:${path}`],workspace,120000,`${prefix}-原始测试`,false);const added=original.exitCode===0?(await this.command(task,['git','diff','--unified=0','--',path],workspace,120000,`${prefix}-测试差异`)).output.split(/\r?\n/).filter(l=>l.startsWith('+')&&!l.startsWith('+++')).map(l=>l.slice(1)).join('\n'):text;for(const marker of settings.forbiddenMarkers)if(added.includes(marker))violations.push(`新增禁止标记 ${marker}：${path}`);if(/assertTrue\s*\(\s*true\s*\)|assertFalse\s*\(\s*false\s*\)/.test(added))violations.push(`新增恒真断言：${path}`);if(original.exitCode===0){if((text.match(/@Test/g)||[]).length<(original.output.match(/@Test/g)||[]).length)violations.push(`测试方法数量减少：${path}`);if((text.match(/\bassert[A-Z]\w*\s*\(/g)||[]).length<(original.output.match(/\bassert[A-Z]\w*\s*\(/g)||[]).length)violations.push(`断言数量减少：${path}`);}}
  return{accepted:!violations.length,changedFiles,violations};}
 private async publish(task:AutoUtTask,workspace:string){if(!settings.createMr)throw new Error('CodeHub MR 创建已被配置关闭。');const guard=await this.inspect(task,workspace,'发布前');if(!guard.accepted)throw new Error(`发布前修改保护未通过：${guard.violations.join('；')}`);await this.command(task,['git','add','--',...guard.changedFiles],workspace,120000,'暂存修改');const title=`[${task.ticket}] 治理 ${task.repository} 单元测试`;await this.command(task,['git','commit','-m',title],workspace,120000,'提交修改');const command=[settings.codehub,'mr','upload','--dest',task.baseBranch,'--br',task.repairBranch,'--topic',task.repairBranch,'-T',title,'-D',`实际修复 ${task.governance?.fixedIds?.length??0} 个失败用例，新增 ${task.governance?.addedIds?.length??0} 个通过用例。\n\n完整 UT 回归通过；覆盖率以合并后质量报告为准。`];const recipients:Array<[string,string]>=[['--reviewers',settings.reviewers],['--approvers',settings.approvers],['--assignees',settings.assignees]];for(const[o,v]of recipients)if(v)command.push(o,v);command.push('-y');const uploaded=await this.command(task,command,workspace,600000,'创建CodeHub-MR');let mr:{id?:unknown;mr_url?:unknown}|undefined;for(const line of [uploaded.output,...uploaded.output.split(/\r?\n/).reverse()])try{const value=JSON.parse(line) as typeof mr;if(value?.id&&value.mr_url){mr=value;break;}}catch{/* next */}if(!mr)throw new Error('CodeHub MR 已上传，但无法从 codehub-cli 输出中读取 id 和 mr_url。');task.pullRequestUrl=String(mr.mr_url);task.nextStage='DONE';task.progress=100;if(task.governance){task.governance.mrState='PENDING';task.governance.completedAt=new Date().toISOString();}this.change(task,'RESOLVED',`已修复 ${task.governance?.fixedIds?.length??0} 个用例，新增 ${task.governance?.addedIds?.length??0} 个用例，MR 待合并。`);}
 private async runPi(task:AutoUtTask,workspace:string,prompt:string){const message=await readFile(prompt,'utf8')+'\n执行修复并在完成后简要说明修改。';this.emit(task,'prompt',message.slice(0,20_000),`attempt-${task.attempts}`,'Pi');const request=JSON.stringify({id:`auto-ut-${task.id}`,type:'prompt',message})+'\n';return runProcess([settings.piCommand,'--mode','rpc','--no-session','--no-context-files','--approve','--thinking',settings.thinkingLevel],workspace,settings.piTimeoutMs,join(settings.logDirectory,task.id,`第${task.attempts}轮-Pi.log`),(line,stderr)=>{if(stderr){this.emit(task,'status',line);return false;}try{const event=JSON.parse(line) as Record<string,unknown>;this.mapPi(task,event);return event.type==='agent_settled'||event.type==='agent_end'&&!event.willRetry;}catch{this.emit(task,'error','无法解析 Pi RPC 事件','','',true);return false;}},request);}
 private mapPi(task:AutoUtTask,event:Record<string,unknown>){const type=String(event.type??'');if(type==='agent_start')this.emit(task,'status','Pi 已开始分析');else if(type==='agent_settled'||type==='agent_end'&&!event.willRetry)this.emit(task,'completed','Pi 执行完成');else if(type==='message_update'){const update=(event.assistantMessageEvent??{}) as Record<string,unknown>;const map:Record<string,string>={thinking_start:'thinking_start',thinking_delta:'thinking_delta',thinking_end:'thinking_end',text_start:'message_start',text_delta:'message_delta',text_end:'message_end'};if(map[String(update.type)])this.emit(task,map[String(update.type)]!,String(update.delta??''));}else if(type==='tool_execution_start')this.emit(task,'tool_start',JSON.stringify(event.args??{}),String(event.toolCallId??''),String(event.toolName??''));else if(type==='tool_execution_update'||type==='tool_execution_end'){const result=(event[type==='tool_execution_update'?'partialResult':'result']??{}) as {content?:Array<{type?:string;text?:string}>};const content=(result.content??[]).filter(i=>i.type==='text').map(i=>i.text??'').join('');this.emit(task,type==='tool_execution_update'?'tool_output':'tool_end',content,String(event.toolCallId??''),String(event.toolName??''),Boolean(event.isError),true);}else if(type==='extension_error'||type==='response'&&event.success===false)this.emit(task,'error',String((event.error as {message?:string})?.message??event.error??'Pi 执行失败'),'','',true);}
 private async files(root:string):Promise<string[]>{const result:string[]=[];const walk=async(dir:string)=>{for(const entry of await readdir(dir,{withFileTypes:true})){const path=join(dir,entry.name);if(entry.isDirectory()&&!['.git','node_modules'].includes(entry.name))await walk(path);else result.push(path);}};await walk(root);return result;}
 private async readSurefire(workspace:string):Promise<UtEvidence>{
  const reports=(await this.files(workspace)).filter(p=>p.replaceAll('\\','/').includes('/target/surefire-reports/TEST-')&&p.endsWith('.xml'));
  if(!reports.length)throw new Error('核验受阻：未生成 Surefire 报告，请检查 Maven 日志。');
  const documents=await Promise.all(reports.map(async path=>({path:relative(workspace,path).replaceAll('\\','/'),content:await readFile(path,'utf8')})));
  const evidence=readUtXml(documents);evidence.details=documents.flatMap(d=>surefireFailureDetails(d.content)).join('\n\n').slice(0,40000);return evidence;
 }

 getSchedule(){return this.store.getRecord<Schedule>('auto-ut-schedule','daily');}saveSchedule(value:Omit<Schedule,'lastTriggeredOn'|'updatedAt'>){const schedule={...value,lastTriggeredOn:null,updatedAt:new Date().toISOString()};this.store.putRecord('auto-ut-schedule','daily',schedule);return this.scheduleResponse(schedule);}deleteSchedule(){this.store.deleteRecord('auto-ut-schedule','daily');}
 scheduleResponse(schedule:Schedule){const{report:_report,...response}=schedule;return response;}private chinaNow(){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts().map(p=>[p.type,p.value]));return{date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`};}
 private async triggerDue(){const schedule=this.getSchedule();if(!schedule)return;const now=this.chinaNow();if(now.time<schedule.dailyTime||now.date===schedule.lastTriggeredOn)return;schedule.lastTriggeredOn=now.date;schedule.updatedAt=new Date().toISOString();this.store.putRecord('auto-ut-schedule','daily',schedule);try{await this.start(Buffer.from(schedule.report,'base64'),schedule.username,schedule.ticket,schedule.baseBranch,schedule.workspaceRoot,'AUTOMATIC');}catch{/* persisted tasks/logs carry operational failure */}}
}

async function multipartFields(request:FastifyRequest){const fields=new Map<string,string>();let file:Buffer|undefined,name='';for await(const part of request.parts({limits:{fileSize:20*1024*1024,files:1,fields:10}})){if(part.type==='file'){name=part.filename??'';file=await part.toBuffer();}else fields.set(part.fieldname,String(part.value));}if(!file)throw Object.assign(new Error('请选择 CSV'),{statusCode:400});return{fields,file,name};}
export async function autoUtRoutes(app:FastifyInstance,service:AutoUtService,schedules?:UnifiedSchedules){await app.register(multipart);const id=(p:unknown)=>z.object({id:z.uuid()}).parse(p).id;
 app.post('/api/auto-ut/scan',async request=>{const{fields,file}=await multipartFields(request);return service.scan(file,fields.get('username')??'',fields.get('ticket')??'',fields.get('baseBranch')??'');});
 app.post('/api/auto-ut/tasks',async(request,reply)=>{const{fields,file}=await multipartFields(request);const mode=z.enum(['MANUAL','AUTOMATIC']).default('AUTOMATIC').parse(fields.get('executionMode'));return reply.code(202).send(await service.start(file,fields.get('username')??'',fields.get('ticket')??'',fields.get('baseBranch')??'',fields.get('workspaceRoot')??'',mode));});
 app.get('/api/auto-ut/governance',async req=>{const q=z.object({version:z.string().optional(),days:z.coerce.number().int().min(0).max(365).default(0)}).parse(req.query);return service.governanceSummary(q.version,q.days);});
 app.post('/api/auto-ut/governance/:id/mr-state',async req=>service.resolveMr(id(req.params),z.object({state:z.enum(['MERGED','CLOSED'])}).parse(req.body).state));
 app.get('/api/auto-ut/tasks',async()=>service.tasks());app.get('/api/auto-ut/tasks/:id',async req=>service.get(id(req.params)));app.post('/api/auto-ut/tasks/:id/continuation',async(req,reply)=>reply.code(202).send(service.continue(id(req.params))));app.delete('/api/auto-ut/tasks/:id',async(req,reply)=>reply.code(200).send(await service.deleteTask(id(req.params))));
 app.put('/api/auto-ut/repositories/:repository',async req=>{const{name}=z.object({name:z.string()}).parse({name:(req.params as{repository?:unknown}).repository});const{url}=z.object({url:z.string().max(2000)}).parse(req.body);return service.saveRepository(name,url);});
 app.get('/api/auto-ut/workspace-directories',async req=>browse(z.object({path:z.string().max(4096).optional()}).parse(req.query).path));
 app.get('/api/auto-ut/tasks/:id/events',async(req,reply)=>{const taskId=id(req.params);service.get(taskId);const query=z.object({afterSequence:z.coerce.number().int().min(0).default(0)}).parse(req.query);const header=z.coerce.number().int().min(0).parse(req.headers['last-event-id']??0);durableSse(reply,n=>service.events(taskId,n),()=>service.terminal(taskId),Math.max(query.afterSequence,header));});
 app.get('/api/auto-ut/schedule',async(_req,reply)=>{const value=service.getSchedule();return value?service.scheduleResponse(value):reply.code(204).send();});
 app.put('/api/auto-ut/schedule',async request=>{const{fields,file,name}=await multipartFields(request),configuredRoot=z.string().trim().min(1,'请配置工作目录').max(4096).parse(fields.get('workspaceRoot'));const value={reportFileName:name,report:file.toString('base64'),username:identity.parse(fields.get('username')),ticket:identity.parse(fields.get('ticket')),baseBranch:branch.parse(fields.get('baseBranch')),workspaceRoot:resolve(configuredRoot),dailyTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).parse(fields.get('dailyTime'))};await stat(value.workspaceRoot).then(s=>{if(!s.isDirectory())throw new Error();}).catch(()=>{throw Object.assign(new Error(`工作目录不存在或不可写：${value.workspaceRoot}`),{statusCode:400});});return schedules?schedules.saveLegacyCsv(value):service.saveSchedule(value);});
 app.delete('/api/auto-ut/schedule',async(_req,reply)=>{if(schedules)schedules.deleteLegacyCsv();else service.deleteSchedule();return reply.code(204).send();});
}
