import type {UnifiedSchedules} from '../automation/schedules.js';
import {randomUUID} from 'node:crypto';
import {readFile,writeFile,mkdir,stat,readdir,unlink,rm} from 'node:fs/promises';
import {resolve,join,relative} from 'node:path';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import multipart from '@fastify/multipart';
import {parse} from 'csv-parse/sync';
import {XMLParser} from 'fast-xml-parser';
import {z} from 'zod';
import type {TaskStore} from '../../platform/store.js';
import {noFileLogs} from '../../infrastructure/file-logs.js';
import type {LogSink} from '../../infrastructure/file-logs.js';
import {runProcess} from '../../infrastructure/process.js';
import {durableSse} from '../../infrastructure/sse.js';
import {browse} from '../workspace/directories.js';

type Mode='MANUAL'|'AUTOMATIC';type Stage='PREPARE'|'BASELINE'|'REPAIR'|'VERIFY'|'PUBLISH'|'DONE';
type Status='DISCOVERED'|'WAITING_CONFIRMATION'|'WAITING_REPOSITORY'|'PREPARING'|'BASELINE_RUNNING'|'REPAIRING'|'VERIFYING'|'RETRY_PENDING'|'WAITING_EXTERNAL'|'PR_CREATING'|'RESOLVED';
interface History{time:string;status:Status;message:string}interface LiveEvent{sequence:number;time:string;type:string;content:string;toolCallId:string;toolName:string;error:boolean;replace:boolean}
interface ReportItem{repository:string;failedTests:number;lineCoverage:number;lineGoal:number;branchCoverage:number;branchGoal:number}
interface Repository{name:string;url:string;testCommand:string[];verificationCommand:string[];coverageReport:string;customized:boolean;updatedAt:string|null}
export interface AutoUtTask{id:string;reportVersion?:string;sourceReportId?:string;repository:string;username:string;ticket:string;baseBranch:string;repairBranch:string;reportedFailedTests:number;lineGoal:number;branchGoal:number;workspaceRoot:string;executionMode:Mode;status:Status;nextStage:Stage;progress:number;attempts:number;message:string;pullRequestUrl:string;createdAt:string;updatedAt:string;history:History[];liveEvents:LiveEvent[];liveSequence:number}
export interface Schedule{reportFileName:string;report:string;username:string;ticket:string;baseBranch:string;workspaceRoot:string;dailyTime:string;lastTriggeredOn:string|null;updatedAt:string}
const identity=z.string().regex(/^[A-Za-z0-9._-]+$/);const branch=z.string().trim().min(1).max(200).regex(/^[A-Za-z0-9][A-Za-z0-9._/-]*$/).refine(v=>!v.includes('..')&&!v.includes('//')&&!v.endsWith('/')&&!v.endsWith('.'));
const settings={language:'Java',plGroup:'Access_智能驾舱组',logDirectory:resolve(process.env.PLATFORM_LOG_DIR?.trim()||'data/logs','auto-ut','details'),piCommand:'pi',thinkingLevel:'medium',piTimeoutMs:30*60_000,maxAttempts:3,
 forbiddenMarkers:['@Disabled','@Ignore'],codehub:'codehub-cli',createMr:true,reviewers:process.env.AUTO_UT_CODEHUB_REVIEWERS?.trim()??'',approvers:process.env.AUTO_UT_CODEHUB_APPROVERS?.trim()??'',assignees:process.env.AUTO_UT_CODEHUB_ASSIGNEES?.trim()??''};
const testCommand=['mvn','-B','-ntp','clean','test'];const verificationCommand=['mvn','-B','-ntp','clean','org.jacoco:jacoco-maven-plugin:0.8.12:prepare-agent','test','org.jacoco:jacoco-maven-plugin:0.8.12:report'];
const stageInfo:Record<Stage,{status:Status;progress:number;message:string}>={PREPARE:{status:'PREPARING',progress:10,message:'正在准备独立 Git 工作区。'},BASELINE:{status:'BASELINE_RUNNING',progress:25,message:'正在执行基线 UT。'},REPAIR:{status:'REPAIRING',progress:45,message:'正在执行 Pi 修复。'},VERIFY:{status:'VERIFYING',progress:70,message:'正在执行完整验证。'},PUBLISH:{status:'PR_CREATING',progress:90,message:'正在提交并创建 CodeHub MR。'},DONE:{status:'RESOLVED',progress:100,message:'任务已完成。'}};

export function autoUtWorkspace(task:Pick<AutoUtTask,'workspaceRoot'|'repository'|'reportVersion'>){
 const root=resolve(task.workspaceRoot);const workspace=task.reportVersion?resolve(root,task.reportVersion,task.repository.toLowerCase()):resolve(root,task.repository.toLowerCase());
 if(relative(root,workspace).startsWith('..'))throw new Error('服务工作目录越界');return workspace;
}

export class AutoUtService{
 private readonly running=new Set<string>();private readonly deleting=new Set<string>();private timer:NodeJS.Timeout;
 constructor(private readonly store:TaskStore,private readonly logs:LogSink=noFileLogs,private readonly ownScheduler=true){for(const task of this.tasks().filter(t=>['DISCOVERED','PREPARING','BASELINE_RUNNING','REPAIRING','VERIFYING','PR_CREATING'].includes(t.status))){this.change(task,'WAITING_EXTERNAL','服务重启，原执行进程已中断，请重试当前阶段。');this.save(task);}
  this.timer=setInterval(()=>{if(this.ownScheduler)void this.triggerDue();},30_000);this.timer.unref();}
 close(){clearInterval(this.timer);}
 private save(task:AutoUtTask){task.updatedAt=new Date().toISOString();this.store.putRecord('auto-ut-task',task.id,task,task.createdAt);}
 private change(task:AutoUtTask,status:Status,message:string){task.status=status;task.message=message;task.updatedAt=new Date().toISOString();const event={time:task.updatedAt,status,message};task.history.push(event);this.logs.task('auto-ut',task.id,{kind:'history',...event});}
 private emit(task:AutoUtTask,type:string,content='',toolCallId='',toolName='',error=false,replace=false){const event={sequence:++task.liveSequence,time:new Date().toISOString(),type,content,toolCallId,toolName,error,replace};
  if(replace&&toolCallId)task.liveEvents=task.liveEvents.filter(e=>!(e.replace&&e.type===type&&e.toolCallId===toolCallId));task.liveEvents.push(event);this.logs.task('auto-ut',task.id,{kind:'live',...event});if(task.liveEvents.length>10000)task.liveEvents.shift();this.save(task);return event;}
 tasks(){return this.store.records<AutoUtTask>('auto-ut-task');}get(id:string){const task=this.store.getRecord<AutoUtTask>('auto-ut-task',id);if(!task)throw Object.assign(new Error('Auto-UT 任务不存在'),{statusCode:404});return task;}
 async deleteTask(id:string){const task=this.get(id);if(this.running.has(id)||this.deleting.has(id))throw Object.assign(new Error('正在执行的 UT 修复任务不能删除'),{statusCode:409});const workspace=autoUtWorkspace(task),shared=this.tasks().find(other=>other.id!==id&&autoUtWorkspace(other)===workspace&&!this.terminalStatus(other.status));if(shared)throw Object.assign(new Error(`工作目录正被未完成任务 ${shared.id} 使用，不能删除`),{statusCode:409});this.deleting.add(id);try{const root=resolve(task.workspaceRoot),boundary=relative(root,workspace);if(!boundary||boundary.startsWith('..')||resolve(root,boundary)!==workspace)throw Object.assign(new Error('任务工作目录不合法，拒绝清理'),{statusCode:409});await rm(workspace,{recursive:true,force:true});await rm(join(settings.logDirectory,id),{recursive:true,force:true});this.store.deleteRecord('auto-ut-task',id);return{id,workspace,workspaceDeleted:true};}catch(error){if(error instanceof Error&&'statusCode' in error)throw error;throw Object.assign(new Error(`UT 修复工作目录清理失败：${error instanceof Error?error.message:'未知错误'}`),{statusCode:409});}finally{this.deleting.delete(id);}}
 async cleanup(retentionDays:number,now=new Date()){const days=z.number().int().min(1).max(365).parse(retentionDays),cutoff=now.getTime()-days*86_400_000;const candidates=this.tasks().filter(task=>Date.parse(task.updatedAt)<cutoff&&['RESOLVED','RETRY_PENDING','WAITING_EXTERNAL','WAITING_REPOSITORY'].includes(task.status));const deleted:string[]=[],failed:Array<{id:string;message:string}>=[];for(const task of candidates)try{await this.deleteTask(task.id);deleted.push(task.id);}catch(error){failed.push({id:task.id,message:error instanceof Error?error.message:'清理失败'});}return{retentionDays,cutoff:new Date(cutoff).toISOString(),deleted,failed};}
 private terminalStatus(status:Status){return!['DISCOVERED','PREPARING','BASELINE_RUNNING','REPAIRING','VERIFYING','PR_CREATING','WAITING_CONFIRMATION','WAITING_EXTERNAL'].includes(status);}
 private repository(name:string):Repository|undefined{if(!/^[A-Za-z0-9._-]+$/.test(name))return;const key=name.toLowerCase();const custom=this.store.getRecord<{url:string;updatedAt:string}>('auto-ut-repository',key);return{name:key,url:custom?.url??`ssh://git@szv-y.codehub.huawei.com:2222/MAE-M/Access/${name}.git`,testCommand,verificationCommand,coverageReport:'target/site/jacoco/jacoco.xml',customized:!!custom,updatedAt:custom?.updatedAt??null};}
 saveRepository(name:string,url:string){if(!/^[A-Za-z0-9._-]+$/.test(name))throw Object.assign(new Error('代码仓名称格式无效'),{statusCode:400});let parsed:URL;try{parsed=new URL(url.trim());}catch{throw Object.assign(new Error('请输入有效的 CodeHub clone URL'),{statusCode:400});}
  if(!['ssh:','https:','http:'].includes(parsed.protocol)||!parsed.hostname.toLowerCase().endsWith('.codehub.huawei.com')||!parsed.pathname.endsWith('.git'))throw Object.assign(new Error('请输入有效的 CodeHub clone URL'),{statusCode:400});
  const updatedAt=new Date().toISOString();this.store.putRecord('auto-ut-repository',name.toLowerCase(),{url:url.trim(),updatedAt});return{repository:name,url:url.trim(),customized:true,updatedAt};}
 parseReport(report:Buffer):ReportItem[]{if(!report.length)throw Object.assign(new Error('CSV 报告不能为空'),{statusCode:400});let rows:Record<string,string>[];try{rows=parse(report,{bom:true,columns:true,skip_empty_lines:true,trim:true});}catch(error){throw Object.assign(new Error(`CSV 报告格式无效：${error instanceof Error?error.message:'解析失败'}`),{statusCode:400});}
  const required=['代码仓','语言','PL组','失败用例','行覆盖率','行覆盖率目标','分支覆盖率','分支覆盖率目标'];const columns=rows[0]?Object.keys(rows[0]):[];const missing=required.filter(c=>!columns.includes(c));if(missing.length)throw Object.assign(new Error(`CSV 缺少必要列：${missing.sort().join('、')}`),{statusCode:400});
  const percent=(v:string)=>{const t=(v??'').trim();return!t?0:t.endsWith('%')?Number(t.slice(0,-1))/100:Number(t);};const items=new Map<string,ReportItem>();for(const row of rows){const repository=row['代码仓']??'';const item={repository,failedTests:Math.trunc(Number(row['失败用例']||0)),lineCoverage:percent(row['行覆盖率']??''),lineGoal:percent(row['行覆盖率目标']??''),branchCoverage:percent(row['分支覆盖率']??''),branchGoal:percent(row['分支覆盖率目标']??'')};
    if(repository&&row['语言']?.toLowerCase()===settings.language.toLowerCase()&&row['PL组']===settings.plGroup&&(item.failedTests>0||item.lineCoverage<item.lineGoal||item.branchCoverage<item.branchGoal))items.set(repository.toLowerCase(),item);}return[...items.values()];}
 scan(report:Buffer,username:string,ticket:string,baseBranch:string){this.validate(username,ticket,baseBranch);return this.parseReport(report).map(item=>{const repository=this.repository(item.repository);return{...item,configured:!!repository,repositoryUrl:repository?.url??'',repositoryCustomized:repository?.customized??false,baseBranch,repairBranch:repository?`${baseBranch}_${username}_${ticket}`:''};});}
 async start(report:Buffer,username:string,ticket:string,baseBranch:string,workspaceRoot:string,executionMode:Mode,source?:{version:string;reportId:string}){this.validate(username,ticket,baseBranch);const root=await this.workspace(workspaceRoot);return this.parseReport(report).map(item=>{const repository=this.repository(item.repository);const now=new Date().toISOString();const task:AutoUtTask={id:randomUUID(),...(source?{reportVersion:source.version,sourceReportId:source.reportId}:{}),repository:item.repository,username,ticket,baseBranch,repairBranch:repository?`${baseBranch}_${username}_${ticket}${source?'_'+source.version:''}`:'',reportedFailedTests:item.failedTests,lineGoal:item.lineGoal,branchGoal:item.branchGoal,workspaceRoot:root,executionMode,status:'DISCOVERED',nextStage:'PREPARE',progress:0,attempts:0,message:'已发现待修复任务',pullRequestUrl:'',createdAt:now,updatedAt:now,history:[],liveEvents:[],liveSequence:0};
    this.change(task,'DISCOVERED','已发现待修复任务');if(!repository)this.change(task,'WAITING_REPOSITORY','代码仓未配置，任务未执行。');this.save(task);if(repository)this.schedule(task,repository);return task;});}
 continue(id:string){const task=this.get(id);if(this.deleting.has(id))throw Object.assign(new Error('任务正在删除，不能继续执行'),{statusCode:409});const repository=this.repository(task.repository);if(!repository)throw Object.assign(new Error('代码仓未配置，任务无法继续。'),{statusCode:409});if(!(task.executionMode==='MANUAL'&&task.status==='WAITING_CONFIRMATION')&&task.status!=='WAITING_EXTERNAL')throw Object.assign(new Error('当前任务不处于可继续或重试的阶段。'),{statusCode:409});this.change(task,'DISCOVERED',`下一阶段已进入执行队列：${stageInfo[task.nextStage].message}`);this.save(task);this.schedule(task,repository);return task;}
 events(id:string,after:number){return this.get(id).liveEvents.filter(e=>e.sequence>after);}terminal(id:string){return this.terminalStatus(this.get(id).status);}
 private validate(username:string,ticket:string,baseBranch:string){identity.parse(username);identity.parse(ticket);branch.parse(baseBranch);}
 private async workspace(value:string){if(!value?.trim())throw Object.assign(new Error('请选择工作目录'),{statusCode:400});const root=resolve(value),probe=join(root,`.container-ops-kit-${randomUUID()}.probe`);try{const info=await stat(root);if(!info.isDirectory())throw new Error();await writeFile(probe,'',{flag:'wx'});await unlink(probe);}catch{await unlink(probe).catch(()=>{});throw Object.assign(new Error(`工作目录不存在或不可写：${root}`),{statusCode:400});}return root;}
 private schedule(task:AutoUtTask,repository:Repository){if(this.running.has(task.id)||this.deleting.has(task.id))return;this.running.add(task.id);void this.execute(task,repository).finally(()=>this.running.delete(task.id));}
 private claim(task:AutoUtTask){if(task.nextStage==='DONE'||!['DISCOVERED','WAITING_CONFIRMATION'].includes(task.status))return false;const info=stageInfo[task.nextStage];if(task.nextStage==='REPAIR')task.attempts++;task.progress=Math.max(task.progress,info.progress);this.change(task,info.status,info.message);this.save(task);return true;}
 private wait(task:AutoUtTask,nextStage:Stage,message:string,progress:number){task.nextStage=nextStage;task.progress=Math.max(task.progress,progress);this.change(task,'WAITING_CONFIRMATION',message);this.save(task);}
 private async execute(task:AutoUtTask,repository:Repository){const workspace=autoUtWorkspace(task);
  try{do{const stage=task.nextStage;if(!this.claim(task))return;if(stage==='PREPARE'){await this.prepare(task,repository,workspace);this.wait(task,'BASELINE',`工作区准备完成：${workspace}`,20);}else if(stage==='BASELINE'){const evidence=await this.baseline(task,repository,workspace);this.change(task,task.status,`基线 UT：共 ${evidence.tests}，失败 ${evidence.failures+evidence.errors}，跳过 ${evidence.skipped}`);if(evidence.failures+evidence.errors!==task.reportedFailedTests)this.change(task,'WAITING_EXTERNAL',`报告显示失败 UT ${task.reportedFailedTests} 个，但本地基线识别到 ${evidence.failures+evidence.errors} 个。`);else{await this.checkoutBranch(task,workspace);this.wait(task,'REPAIR','基线确认完成，修复分支已就绪。',35);}}else if(stage==='REPAIR')await this.repair(task,workspace);else if(stage==='VERIFY')await this.verify(task,repository,workspace);else if(stage==='PUBLISH')await this.publish(task,workspace);this.save(task);}while(task.executionMode==='AUTOMATIC'&&task.status==='WAITING_CONFIRMATION');}
  catch(error){this.change(task,'WAITING_EXTERNAL',error instanceof Error?error.message:'Auto-UT 执行异常');this.save(task);}}
 private async command(task:AutoUtTask,command:string[],directory:string,timeout:number,label:string,required=true){const id=randomUUID();this.emit(task,'operation_start',label,id,command.join(' '));const safe=label.replace(/[^\p{L}\p{N}._-]/gu,'_');try{const result=await runProcess(command,directory,timeout,join(settings.logDirectory,task.id,`${safe}.log`));this.emit(task,'operation_end',label,id,'',result.exitCode!==0);if(required&&result.exitCode!==0)throw new Error(`${label}失败，退出码 ${result.exitCode}：${result.output.slice(0,2000)}`);return result;}catch(error){this.emit(task,'operation_end',label,id,'',true);throw error;}}
 private async prepare(task:AutoUtTask,repository:Repository,workspace:string){await mkdir(resolve(workspace,'..'),{recursive:true});const exists=await stat(workspace).then(()=>true).catch(()=>false);if(exists){const git=await this.command(task,['git','rev-parse','--git-dir'],workspace,120000,'检查Git仓库');if(git.exitCode!==0)throw new Error(`工作目录不是 Git 仓库：${workspace}`);const origin=(await this.command(task,['git','remote','get-url','origin'],workspace,120000,'检查远端')).output.trim();if(origin.replace(/\/+$/,'').toLowerCase()!==repository.url.replace(/\/+$/,'').toLowerCase())throw new Error(`工作目录的 origin 与配置不一致：${workspace}`);if((await this.command(task,['git','status','--porcelain'],workspace,120000,'准备状态')).output.trim())throw new Error(`工作目录存在未提交修改，请先处理：${workspace}`);await this.command(task,['git','fetch','origin'],workspace,600000,'拉取仓库');}else await this.command(task,['git','clone','--branch',task.baseBranch,repository.url,workspace],resolve(workspace,'..'),600000,'克隆仓库');
  await this.command(task,['git','checkout',task.baseBranch],workspace,120000,'检出基础分支');await this.command(task,['git','pull','--ff-only','origin',task.baseBranch],workspace,600000,'更新基础分支');}
 private async baseline(task:AutoUtTask,repository:Repository,workspace:string){await this.command(task,repository.testCommand,workspace,1800000,'基线测试',false);return this.readSurefire(workspace);}
 private async checkoutBranch(task:AutoUtTask,workspace:string){const local=await this.command(task,['git','show-ref','--verify','--quiet',`refs/heads/${task.repairBranch}`],workspace,120000,'查询本地修复分支',false);if(local.exitCode===0){await this.command(task,['git','checkout',task.repairBranch],workspace,120000,'复用本地修复分支');return;}const remote=await this.command(task,['git','ls-remote','--exit-code','--heads','origin',task.repairBranch],workspace,120000,'查询远端修复分支',false);await this.command(task,remote.exitCode===0?['git','checkout','-B',task.repairBranch,`origin/${task.repairBranch}`]:['git','checkout','-b',task.repairBranch],workspace,120000,remote.exitCode===0?'复用远端修复分支':'创建修复分支');}
 private async repair(task:AutoUtTask,workspace:string){const evidence=await this.readSurefire(workspace);const dir=join(settings.logDirectory,task.id);await mkdir(dir,{recursive:true});const prompt=join(dir,`第${task.attempts}轮提示词.md`);await writeFile(prompt,[`你正在修复 Java 项目的单元测试。`,'只能修改或新增 src/test 目录中的文件，禁止修改生产代码、构建文件和门禁配置。','禁止删除测试、禁用测试、弱化或移除有效断言。请定位失败原因并修正测试。',`报告中的失败用例数：${task.reportedFailedTests}`,`行覆盖率目标：${task.lineGoal}`,`分支覆盖率目标：${task.branchGoal}`,'基线失败证据：',evidence.details||'未提取到详细失败堆栈，请读取 Surefire 报告。'].join('\n'),'utf8');
  const result=await this.runPi(task,workspace,prompt);if(result.exitCode!==0){this.retry(task,`第 ${task.attempts} 轮 Pi 执行失败。`);return;}const guard=await this.inspect(task,workspace,`第${task.attempts}轮`);if(!guard.accepted){await this.command(task,['git','stash','push','--include-untracked','-m',`auto-ut拒绝-${task.id}-第${task.attempts}轮`],workspace,120000,'隔离违规修改');this.retry(task,`修改门禁未通过：${guard.violations.join('；')}`);return;}this.change(task,task.status,`修改门禁通过：${guard.changedFiles.length} 个测试文件`);this.wait(task,'VERIFY',`第 ${task.attempts} 轮修复完成，等待完整验证。`,60);}
 private retry(task:AutoUtTask,message:string){if(task.attempts>=settings.maxAttempts)this.change(task,'RETRY_PENDING',`${message} 已达到最大修复轮次。`);else this.wait(task,'REPAIR',`${message} 等待下一轮修复。`,60);}
 private async verify(task:AutoUtTask,repository:Repository,workspace:string){const result=await this.command(task,repository.verificationCommand,workspace,1800000,`第${task.attempts}轮-完整验证`,false);const evidence=await this.readSurefire(workspace);const coverage=result.exitCode===0?await this.readCoverage(join(workspace,repository.coverageReport)):{line:0,branch:0};this.change(task,task.status,`完整验证：共 ${evidence.tests}，失败 ${evidence.failures+evidence.errors}，跳过 ${evidence.skipped}，行覆盖率 ${(coverage.line*100).toFixed(2)}%，分支覆盖率 ${(coverage.branch*100).toFixed(2)}%`);
  if(result.exitCode===0&&!evidence.failures&&!evidence.errors&&!evidence.skipped&&coverage.line>=task.lineGoal&&coverage.branch>=task.branchGoal)this.wait(task,'PUBLISH','完整 UT 与覆盖率验证通过。',85);else this.retry(task,result.exitCode!==0?'完整验证命令执行失败。':evidence.failures+evidence.errors||evidence.skipped?`验证未通过：失败 ${evidence.failures+evidence.errors}，跳过 ${evidence.skipped}。`:`覆盖率未达标：行 ${(coverage.line*100).toFixed(2)}%/${(task.lineGoal*100).toFixed(2)}%，分支 ${(coverage.branch*100).toFixed(2)}%/${(task.branchGoal*100).toFixed(2)}%。`);}
 private async inspect(task:AutoUtTask,workspace:string,prefix:string){const status=(await this.command(task,['git','-c','core.quotepath=false','status','--porcelain','--untracked-files=all'],workspace,120000,`${prefix}-修改状态`)).output;const changedFiles:string[]=[];const violations:string[]=[];for(const line of status.split(/\r?\n/)){if(line.length<4)continue;let path=line.slice(3).replaceAll('\\','/');if(path.includes(' -> '))path=path.slice(path.indexOf(' -> ')+4);changedFiles.push(path);if(!(path.startsWith('src/test/')||path.includes('/src/test/')))violations.push(`越界修改：${path}`);if(line.slice(0,2).trim()==='D')violations.push(`禁止删除测试文件：${path}`);}if(!changedFiles.length)violations.push('Pi 未产生任何文件修改。');
  for(const path of changedFiles){const file=resolve(workspace,path);if(relative(workspace,file).startsWith('..'))continue;let text;try{text=await readFile(file,'utf8');}catch{continue;}const original=await this.command(task,['git','show',`HEAD:${path}`],workspace,120000,`${prefix}-原始测试`,false);const added=original.exitCode===0?(await this.command(task,['git','diff','--unified=0','--',path],workspace,120000,`${prefix}-测试差异`)).output.split(/\r?\n/).filter(l=>l.startsWith('+')&&!l.startsWith('+++')).map(l=>l.slice(1)).join('\n'):text;for(const marker of settings.forbiddenMarkers)if(added.includes(marker))violations.push(`新增禁止标记 ${marker}：${path}`);if(/assertTrue\s*\(\s*true\s*\)|assertFalse\s*\(\s*false\s*\)/.test(added))violations.push(`新增恒真断言：${path}`);if(original.exitCode===0){if((text.match(/@Test/g)||[]).length<(original.output.match(/@Test/g)||[]).length)violations.push(`测试方法数量减少：${path}`);if((text.match(/\bassert[A-Z]\w*\s*\(/g)||[]).length<(original.output.match(/\bassert[A-Z]\w*\s*\(/g)||[]).length)violations.push(`断言数量减少：${path}`);}}
  return{accepted:!violations.length,changedFiles,violations};}
 private async publish(task:AutoUtTask,workspace:string){if(!settings.createMr)throw new Error('CodeHub MR 创建已被配置关闭。');const guard=await this.inspect(task,workspace,'发布前');if(!guard.accepted)throw new Error(`发布前修改保护未通过：${guard.violations.join('；')}`);await this.command(task,['git','add','--',...guard.changedFiles],workspace,120000,'暂存修改');const title=`[${task.ticket}] 修复 ${task.repository} 单元测试`;await this.command(task,['git','commit','-m',title],workspace,120000,'提交修改');const command=[settings.codehub,'mr','upload','--dest',task.baseBranch,'--br',task.repairBranch,'--topic',task.repairBranch,'-T',title,'-D',`自动修复 ${task.reportedFailedTests} 个失败单元测试。\n\n完整 UT 与覆盖率验证已通过。`];const recipients:Array<[string,string]>=[['--reviewers',settings.reviewers],['--approvers',settings.approvers],['--assignees',settings.assignees]];for(const[o,v]of recipients)if(v)command.push(o,v);command.push('-y');const uploaded=await this.command(task,command,workspace,600000,'创建CodeHub-MR');let mr:{id?:unknown;mr_url?:unknown}|undefined;for(const line of [uploaded.output,...uploaded.output.split(/\r?\n/).reverse()])try{const value=JSON.parse(line) as typeof mr;if(value?.id&&value.mr_url){mr=value;break;}}catch{/* next */}if(!mr)throw new Error('CodeHub MR 已上传，但无法从 codehub-cli 输出中读取 id 和 mr_url。');task.pullRequestUrl=String(mr.mr_url);task.nextStage='DONE';task.progress=100;this.change(task,'RESOLVED','修复验证通过且 CodeHub MR 已创建。');}
 private async runPi(task:AutoUtTask,workspace:string,prompt:string){const message=await readFile(prompt,'utf8')+'\n执行修复并在完成后简要说明修改。';this.emit(task,'prompt',message.slice(0,20_000),`attempt-${task.attempts}`,'Pi');const request=JSON.stringify({id:`auto-ut-${task.id}`,type:'prompt',message})+'\n';return runProcess([settings.piCommand,'--mode','rpc','--no-session','--no-context-files','--approve','--thinking',settings.thinkingLevel],workspace,settings.piTimeoutMs,join(settings.logDirectory,task.id,`第${task.attempts}轮-Pi.log`),(line,stderr)=>{if(stderr){this.emit(task,'status',line);return false;}try{const event=JSON.parse(line) as Record<string,unknown>;this.mapPi(task,event);return event.type==='agent_settled'||event.type==='agent_end'&&!event.willRetry;}catch{this.emit(task,'error','无法解析 Pi RPC 事件','','',true);return false;}},request);}
 private mapPi(task:AutoUtTask,event:Record<string,unknown>){const type=String(event.type??'');if(type==='agent_start')this.emit(task,'status','Pi 已开始分析');else if(type==='agent_settled'||type==='agent_end'&&!event.willRetry)this.emit(task,'completed','Pi 执行完成');else if(type==='message_update'){const update=(event.assistantMessageEvent??{}) as Record<string,unknown>;const map:Record<string,string>={thinking_start:'thinking_start',thinking_delta:'thinking_delta',thinking_end:'thinking_end',text_start:'message_start',text_delta:'message_delta',text_end:'message_end'};if(map[String(update.type)])this.emit(task,map[String(update.type)]!,String(update.delta??''));}else if(type==='tool_execution_start')this.emit(task,'tool_start',JSON.stringify(event.args??{}),String(event.toolCallId??''),String(event.toolName??''));else if(type==='tool_execution_update'||type==='tool_execution_end'){const result=(event[type==='tool_execution_update'?'partialResult':'result']??{}) as {content?:Array<{type?:string;text?:string}>};const content=(result.content??[]).filter(i=>i.type==='text').map(i=>i.text??'').join('');this.emit(task,type==='tool_execution_update'?'tool_output':'tool_end',content,String(event.toolCallId??''),String(event.toolName??''),Boolean(event.isError),true);}else if(type==='extension_error'||type==='response'&&event.success===false)this.emit(task,'error',String((event.error as {message?:string})?.message??event.error??'Pi 执行失败'),'','',true);}
 private async files(root:string):Promise<string[]>{const result:string[]=[];const walk=async(dir:string)=>{for(const entry of await readdir(dir,{withFileTypes:true})){const path=join(dir,entry.name);if(entry.isDirectory())await walk(path);else result.push(path);}};await walk(root);return result;}
 private async readSurefire(workspace:string){const reports=(await this.files(workspace)).filter(p=>p.replaceAll('\\','/').includes('/target/surefire-reports/TEST-')&&p.endsWith('.xml'));if(!reports.length)throw new Error('未找到 Maven Surefire XML 测试报告。');let tests=0,failures=0,errors=0,skipped=0;const details:string[]=[];const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_',allowBooleanAttributes:true});for(const path of reports){const xml=parser.parse(await readFile(path,'utf8')) as Record<string,unknown>;const suite=(xml.testsuite??xml.testsuites) as Record<string,unknown>;tests+=Number(suite?.['@_tests']??0);failures+=Number(suite?.['@_failures']??0);errors+=Number(suite?.['@_errors']??0);skipped+=Number(suite?.['@_skipped']??0);if((suite?.['@_failures']??0)||(suite?.['@_errors']??0))details.push((await readFile(path,'utf8')).slice(0,4000));}return{tests,failures,errors,skipped,details:details.join('\n\n')};}
 private async readCoverage(path:string){let content;try{content=await readFile(path,'utf8');}catch{throw new Error(`未找到 JaCoCo 报告：${path}`);}let line=0,branchValue=1;for(const match of content.matchAll(/<counter\s+type="(LINE|BRANCH)"\s+missed="(\d+)"\s+covered="(\d+)"\s*\/>/g)){const missed=Number(match[2]),covered=Number(match[3]),ratio=covered+missed===0?1:covered/(covered+missed);if(match[1]==='LINE')line=ratio;else branchValue=ratio;}return{line,branch:branchValue};}
 getSchedule(){return this.store.getRecord<Schedule>('auto-ut-schedule','daily');}saveSchedule(value:Omit<Schedule,'lastTriggeredOn'|'updatedAt'>){const schedule={...value,lastTriggeredOn:null,updatedAt:new Date().toISOString()};this.store.putRecord('auto-ut-schedule','daily',schedule);return this.scheduleResponse(schedule);}deleteSchedule(){this.store.deleteRecord('auto-ut-schedule','daily');}
 scheduleResponse(schedule:Schedule){const{report:_report,...response}=schedule;return response;}private chinaNow(){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts().map(p=>[p.type,p.value]));return{date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`};}
 private async triggerDue(){const schedule=this.getSchedule();if(!schedule)return;const now=this.chinaNow();if(now.time<schedule.dailyTime||now.date===schedule.lastTriggeredOn)return;schedule.lastTriggeredOn=now.date;schedule.updatedAt=new Date().toISOString();this.store.putRecord('auto-ut-schedule','daily',schedule);try{await this.start(Buffer.from(schedule.report,'base64'),schedule.username,schedule.ticket,schedule.baseBranch,schedule.workspaceRoot,'AUTOMATIC');}catch{/* persisted tasks/logs carry operational failure */}}
}

async function multipartFields(request:FastifyRequest){const fields=new Map<string,string>();let file:Buffer|undefined,name='';for await(const part of request.parts({limits:{fileSize:20*1024*1024,files:1,fields:10}})){if(part.type==='file'){name=part.filename??'';file=await part.toBuffer();}else fields.set(part.fieldname,String(part.value));}if(!file)throw Object.assign(new Error('请选择 CSV'),{statusCode:400});return{fields,file,name};}
export async function autoUtRoutes(app:FastifyInstance,service:AutoUtService,schedules?:UnifiedSchedules){await app.register(multipart);const id=(p:unknown)=>z.object({id:z.uuid()}).parse(p).id;
 app.post('/api/auto-ut/scan',async request=>{const{fields,file}=await multipartFields(request);return service.scan(file,fields.get('username')??'',fields.get('ticket')??'',fields.get('baseBranch')??'');});
 app.post('/api/auto-ut/tasks',async(request,reply)=>{const{fields,file}=await multipartFields(request);const mode=z.enum(['MANUAL','AUTOMATIC']).default('AUTOMATIC').parse(fields.get('executionMode'));return reply.code(202).send(await service.start(file,fields.get('username')??'',fields.get('ticket')??'',fields.get('baseBranch')??'',fields.get('workspaceRoot')??'',mode));});
 app.get('/api/auto-ut/tasks',async()=>service.tasks());app.get('/api/auto-ut/tasks/:id',async req=>service.get(id(req.params)));app.post('/api/auto-ut/tasks/:id/continuation',async(req,reply)=>reply.code(202).send(service.continue(id(req.params))));app.delete('/api/auto-ut/tasks/:id',async(req,reply)=>reply.code(200).send(await service.deleteTask(id(req.params))));
 app.put('/api/auto-ut/repositories/:repository',async req=>{const{name}=z.object({name:z.string()}).parse({name:(req.params as{repository?:unknown}).repository});const{url}=z.object({url:z.string().max(2000)}).parse(req.body);return service.saveRepository(name,url);});
 app.get('/api/auto-ut/workspace-directories',async req=>browse(z.object({path:z.string().max(4096).optional()}).parse(req.query).path));
 app.get('/api/auto-ut/tasks/:id/events',async(req,reply)=>{const taskId=id(req.params);service.get(taskId);const query=z.object({afterSequence:z.coerce.number().int().min(0).default(0)}).parse(req.query);const header=z.coerce.number().int().min(0).parse(req.headers['last-event-id']??0);durableSse(reply,n=>service.events(taskId,n),()=>service.terminal(taskId),Math.max(query.afterSequence,header));});
 app.get('/api/auto-ut/schedule',async(_req,reply)=>{const value=service.getSchedule();return value?service.scheduleResponse(value):reply.code(204).send();});
 app.put('/api/auto-ut/schedule',async request=>{const{fields,file,name}=await multipartFields(request);const value={reportFileName:name,report:file.toString('base64'),username:identity.parse(fields.get('username')),ticket:identity.parse(fields.get('ticket')),baseBranch:branch.parse(fields.get('baseBranch')),workspaceRoot:resolve(fields.get('workspaceRoot')??''),dailyTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).parse(fields.get('dailyTime'))};await stat(value.workspaceRoot).then(s=>{if(!s.isDirectory())throw new Error();}).catch(()=>{throw Object.assign(new Error(`工作目录不存在或不可写：${value.workspaceRoot}`),{statusCode:400});});return schedules?schedules.saveLegacyCsv(value):service.saveSchedule(value);});
 app.delete('/api/auto-ut/schedule',async(_req,reply)=>{if(schedules)schedules.deleteLegacyCsv();else service.deleteSchedule();return reply.code(204).send();});
}
